// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AccountVerificationResponse
 */
export type AccountVerificationResponse = {
    /**
     * Message
     */
    message: string;
    /**
     * Redirect
     */
    redirect: boolean;
    /**
     * Token
     */
    token: string;
    user: User;
};

/**
 * AdminAttemptDetailResponse
 * The per-question breakdown of a single attempt for the admin drill-in,
 * with enough header context (who / which set) to read on its own.
 */
export type AdminAttemptDetailResponse = {
    /**
     * Attemptid
     */
    attemptId: string;
    /**
     * Studentemail
     */
    studentEmail?: string | null;
    /**
     * Settitle
     */
    setTitle?: string | null;
    /**
     * Subject
     */
    subject?: string | null;
    /**
     * Status
     */
    status: 'in_progress' | 'submitted' | 'timed_out' | 'abandoned';
    /**
     * Totalscore
     */
    totalScore?: number | null;
    /**
     * Rows
     */
    rows: Array<AdminAttemptDetailRow>;
};

/**
 * AdminAttemptDetailRow
 * One question within an attempt, as an admin drilling in sees it: what
 * the student picked vs. the correct option, whether it was right, and the
 * per-question pacing (time, views, flag).
 */
export type AdminAttemptDetailRow = {
    /**
     * Questionorderindex
     */
    questionOrderIndex: number;
    /**
     * Questionid
     */
    questionId: string;
    /**
     * Stem
     */
    stem?: string | null;
    /**
     * Topiccode
     */
    topicCode?: string | null;
    /**
     * Coreskillprimary
     */
    coreSkillPrimary?: string | null;
    /**
     * Selectedoption
     */
    selectedOption?: string | null;
    /**
     * Correctoption
     */
    correctOption?: string | null;
    /**
     * Iscorrect
     */
    isCorrect?: boolean | null;
    /**
     * Totaltimeseconds
     */
    totalTimeSeconds: number;
    /**
     * Viewcount
     */
    viewCount: number;
    /**
     * Isflagged
     */
    isFlagged: boolean;
};

/**
 * AdminAttemptResultRow
 * One attempt in the admin results table — a student's sitting of a set,
 * enriched with who took it (email; public.users has no name) and which set
 * (title + subject), so an admin can collect and compare results across
 * everyone who attempted a diagnostic. total_time_seconds is the engaged
 * time summed over the attempt's responses; answered_count / question_count
 * give completion.
 */
export type AdminAttemptResultRow = {
    /**
     * Attemptid
     */
    attemptId: string;
    /**
     * Studentid
     */
    studentId: string;
    /**
     * Studentemail
     */
    studentEmail?: string | null;
    /**
     * Setid
     */
    setId: string;
    /**
     * Settitle
     */
    setTitle?: string | null;
    /**
     * Subject
     */
    subject?: string | null;
    /**
     * Status
     */
    status: 'in_progress' | 'submitted' | 'timed_out' | 'abandoned';
    /**
     * Totalscore
     */
    totalScore?: number | null;
    /**
     * Answeredcount
     */
    answeredCount: number;
    /**
     * Questioncount
     */
    questionCount: number;
    /**
     * Startedat
     */
    startedAt: string;
    /**
     * Submittedat
     */
    submittedAt?: string | null;
    /**
     * Totaltimeseconds
     */
    totalTimeSeconds: number;
};

/**
 * AdminAttemptResultsResponse
 * Every attempt, newest first — the source for the admin results table
 * and its CSV export.
 */
export type AdminAttemptResultsResponse = {
    /**
     * Rows
     */
    rows: Array<AdminAttemptResultRow>;
};

/**
 * AttemptRadarResponse
 * GET /attempts/{id}/radar — Season Pass only (402 otherwise). The
 * per-skill rollup with misconception narratives, i.e. the 'why' the free
 * report deliberately withholds.
 */
export type AttemptRadarResponse = {
    /**
     * Attemptid
     */
    attemptId: string;
    /**
     * Subject
     */
    subject?: string | null;
    /**
     * Skills
     */
    skills: Array<SkillRadarDetail>;
};

/**
 * BaseLevel
 */
export type BaseLevel = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
};

/**
 * BaseSubject
 */
export type BaseSubject = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Code
     */
    code: string;
    /**
     * Topics
     */
    topics: Array<BaseTopic>;
    /**
     * Papers
     */
    papers: Array<Paper>;
    /**
     * Ispublished
     */
    isPublished?: boolean;
};

/**
 * BaseSyllabus
 */
export type BaseSyllabus = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Code
     */
    code: string;
};

/**
 * BaseTopic
 */
export type BaseTopic = {
    /**
     * Id
     */
    id: string;
    level?: BaseLevel | null;
    /**
     * Name
     */
    name: string;
    /**
     * Sortorder
     */
    sortOrder: number;
};

/**
 * Body_convert_latex_converter_post
 */
export type BodyConvertLatexConverterPost = {
    /**
     * File
     * LaTeX file to convert
     */
    file: Blob | File;
    /**
     * Title
     * Document title
     */
    title: string;
    /**
     * Difficulty
     * Document difficulty level
     */
    difficulty: string;
    /**
     * Topics
     * List of Topic Ids
     */
    topics: Array<string>;
    /**
     * Paper Instance Id
     * Paper instance ID
     */
    paper_instance_id: string;
    /**
     * Number
     * Question number within paper
     */
    number: number;
    /**
     * Marks
     * Marks allocated for this question
     */
    marks?: number | null;
    /**
     * Question Type
     * Type of question
     */
    question_type: 'default' | 'multiple_choice';
};

/**
 * Body_upload_diagnostic_question_diagram_diagnostic_questions__question_id__diagram_post
 */
export type BodyUploadDiagnosticQuestionDiagramDiagnosticQuestionsQuestionIdDiagramPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * BulkDeleteAttemptsBody
 * Delete several attempts (results) at once — the multi-select delete on
 * the admin Results table. Each attempt's responses and question-events are
 * removed too (FK ON DELETE CASCADE).
 */
export type BulkDeleteAttemptsBody = {
    /**
     * Attemptids
     */
    attemptIds: Array<string>;
};

/**
 * BulkDeleteAttemptsResponse
 */
export type BulkDeleteAttemptsResponse = {
    /**
     * Deletedcount
     */
    deletedCount: number;
};

/**
 * BulkImportOption
 */
export type BulkImportOption = {
    /**
     * Label
     */
    label: string;
    /**
     * Text
     */
    text: string;
    /**
     * Iscorrect
     */
    isCorrect?: boolean;
    /**
     * Misconception
     */
    misconception?: string | null;
};

/**
 * BulkImportQuestion
 */
export type BulkImportQuestion = {
    /**
     * Sourceref
     */
    sourceRef: string;
    /**
     * Topiccode
     */
    topicCode: string;
    /**
     * Coreskillprimary
     */
    coreSkillPrimary: string;
    /**
     * Coreskillsecondary
     */
    coreSkillSecondary?: string | null;
    /**
     * Difficultytag
     */
    difficultyTag?: string | null;
    /**
     * Stem
     */
    stem: string;
    /**
     * Options
     */
    options: Array<BulkImportOption>;
    /**
     * Correctoption
     */
    correctOption: string;
    /**
     * Diagramsvg
     */
    diagramSvg?: string | null;
    /**
     * Status
     */
    status?: 'draft' | 'published';
    /**
     * Note
     */
    note?: string | null;
};

/**
 * BulkImportRequest
 */
export type BulkImportRequest = {
    diagnosticSet: BulkImportSetMeta;
    /**
     * Questions
     */
    questions: Array<BulkImportQuestion>;
};

/**
 * BulkImportResponse
 */
export type BulkImportResponse = {
    /**
     * Issuccess
     */
    isSuccess: boolean;
    /**
     * Message
     */
    message: string;
    /**
     * Diagnosticsetid
     */
    diagnosticSetId: string;
    /**
     * Questionids
     */
    questionIds: Array<string>;
    /**
     * Questioncount
     */
    questionCount: number;
};

/**
 * BulkImportSetMeta
 */
export type BulkImportSetMeta = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Timelimitminutes
     */
    timeLimitMinutes: number;
    /**
     * Isfree
     */
    isFree?: boolean;
    /**
     * Subject
     */
    subject?: string | null;
    /**
     * Questionorder
     */
    questionOrder: Array<string>;
};

/**
 * BulkPublishBody
 * Publish (or unpublish) several questions at once.
 *
 * Named apart from the diagnostic router's BulkQuestionStatusBody on purpose:
 * two Pydantic models sharing a name make the OpenAPI generator disambiguate
 * *both* into AppModels-prefixed type names, silently renaming the diagnostic
 * type the frontend already imports.
 *
 * Publishing several at once — the action that ends
 * a review pass, so an admin doesn't click through 55 questions one at a
 * time to release a batch.
 */
export type BulkPublishBody = {
    /**
     * Questionids
     */
    questionIds: Array<string>;
    /**
     * Status
     */
    status: 'draft' | 'published';
};

/**
 * BulkPublishResponse
 */
export type BulkPublishResponse = {
    /**
     * Updatedcount
     */
    updatedCount: number;
};

/**
 * BulkQuestionStatusBody
 * Publish (or unpublish) several questions in one call — powers the
 * 'publish all questions in this set' action, so an admin doesn't edit 27
 * questions one at a time to get a set past its publish gate.
 */
export type BulkQuestionStatusBody = {
    /**
     * Questionids
     */
    questionIds: Array<string>;
    /**
     * Status
     */
    status: 'draft' | 'published';
};

/**
 * BulkQuestionStatusResponse
 */
export type BulkQuestionStatusResponse = {
    /**
     * Updatedcount
     */
    updatedCount: number;
};

/**
 * ConversionResponse
 */
export type ConversionResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Documentid
     */
    documentId: string;
    /**
     * Message
     */
    message: string;
};

/**
 * CreateDiagnosticQuestionBody
 */
export type CreateDiagnosticQuestionBody = {
    /**
     * Topiccode
     */
    topicCode: string;
    /**
     * Coreskillprimary
     */
    coreSkillPrimary: string;
    /**
     * Coreskillsecondary
     */
    coreSkillSecondary?: string | null;
    /**
     * Stem
     */
    stem: string;
    /**
     * Options
     */
    options: Array<DiagnosticOption>;
    /**
     * Correctoption
     */
    correctOption: string;
    /**
     * Difficultytag
     */
    difficultyTag?: string | null;
    /**
     * Status
     */
    status?: 'draft' | 'published';
    /**
     * Diagramsvg
     */
    diagramSvg?: string | null;
};

/**
 * CreateDiagnosticSetBody
 * Compose a set by hand (§3), as an alternative to bulk import. Lands
 * as draft. question_ids may be empty — a set is created loose and filled
 * later; the ≥1-question rule is enforced at the publish gate, not here.
 * Order is the question sequence.
 */
export type CreateDiagnosticSetBody = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Timelimitminutes
     */
    timeLimitMinutes: number;
    /**
     * Isfree
     */
    isFree?: boolean;
    /**
     * Subject
     */
    subject?: string | null;
    /**
     * Questionids
     */
    questionIds?: Array<string>;
};

/**
 * CreateLevelBody
 */
export type CreateLevelBody = {
    /**
     * Name
     */
    name: string;
    /**
     * Syllabusid
     */
    syllabusId: string;
};

/**
 * CreateOptionBody
 */
export type CreateOptionBody = {
    /**
     * Value
     */
    value: string;
    /**
     * Iscorrect
     */
    isCorrect?: boolean;
    /**
     * Position
     */
    position?: number;
};

/**
 * CreatePaperBody
 */
export type CreatePaperBody = {
    /**
     * Name
     */
    name: string;
    /**
     * Subjectid
     */
    subjectId: string;
};

/**
 * CreatePaperInstanceBody
 */
export type CreatePaperInstanceBody = {
    /**
     * Paperid
     */
    paperId: string;
    /**
     * Variantid
     */
    variantId: string;
};

/**
 * CreatePaperVariantBody
 */
export type CreatePaperVariantBody = {
    /**
     * Name
     */
    name: string;
    /**
     * Year
     */
    year: number;
    /**
     * Syllabusid
     */
    syllabusId: string;
};

/**
 * CreateSubjectBody
 */
export type CreateSubjectBody = {
    /**
     * Name
     */
    name: string;
    /**
     * Code
     */
    code: string;
    /**
     * Syllabusid
     */
    syllabusId: string;
};

/**
 * CreateSyllabusBody
 */
export type CreateSyllabusBody = {
    /**
     * Name
     */
    name: string;
    /**
     * Code
     */
    code: string;
};

/**
 * CreateTopicBody
 */
export type CreateTopicBody = {
    /**
     * Name
     */
    name: string;
    /**
     * Levelid
     */
    levelId?: string | null;
    /**
     * Subjectid
     */
    subjectId: string;
    /**
     * Sortorder
     */
    sortOrder: number;
};

/**
 * DiagnosticAttemptResponse
 */
export type DiagnosticAttemptResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Diagnosticsetid
     */
    diagnosticSetId: string;
    /**
     * Status
     */
    status: 'in_progress' | 'submitted' | 'timed_out' | 'abandoned';
    /**
     * Startedat
     */
    startedAt: string;
    /**
     * Serverdeadlineat
     */
    serverDeadlineAt: string;
    /**
     * Submittedat
     */
    submittedAt?: string | null;
    /**
     * Agreedtoterms
     */
    agreedToTerms: boolean;
    /**
     * Totalscore
     */
    totalScore?: number | null;
};

/**
 * DiagnosticAttemptStateResponse
 * Returned by both POST /diagnostic/attempts (start-or-resume) and GET
 * /diagnostic/attempts/{id} (rehydrate) — same shape either way, since a
 * resumed attempt's initial state and a reconnect's rehydrated state are
 * the same question the frontend is asking: 'where do things stand right
 * now.'
 */
export type DiagnosticAttemptStateResponse = {
    attempt: DiagnosticAttemptResponse;
    /**
     * Questions
     */
    questions: Array<StudentDiagnosticQuestionResponse>;
    /**
     * Responses
     */
    responses: Array<DiagnosticResponseState>;
};

/**
 * DiagnosticOption
 */
export type DiagnosticOption = {
    /**
     * Label
     */
    label: string;
    /**
     * Text
     */
    text: string;
    /**
     * Iscorrect
     */
    isCorrect?: boolean;
    /**
     * Misconception
     */
    misconception?: string | null;
};

/**
 * DiagnosticQuestionEvent
 */
export type DiagnosticQuestionEvent = {
    /**
     * Questionid
     */
    questionId: string;
    /**
     * Eventtype
     */
    eventType: 'enter' | 'exit' | 'flag' | 'unflag' | 'answer_change' | 'blur' | 'focus';
    /**
     * Clientts
     */
    clientTs?: string | null;
};

/**
 * DiagnosticQuestionResponse
 */
export type DiagnosticQuestionResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Topiccode
     */
    topicCode: string;
    /**
     * Coreskillprimary
     */
    coreSkillPrimary: string;
    /**
     * Coreskillsecondary
     */
    coreSkillSecondary?: string | null;
    /**
     * Stem
     */
    stem: string;
    /**
     * Options
     */
    options: Array<DiagnosticOption>;
    /**
     * Correctoption
     */
    correctOption: string;
    /**
     * Diagramurl
     */
    diagramUrl?: string | null;
    /**
     * Difficultytag
     */
    difficultyTag?: string | null;
    /**
     * Status
     */
    status: 'draft' | 'published';
    /**
     * Createdat
     */
    createdAt: string;
};

/**
 * DiagnosticReportResponse
 * The post-exam report (§6): Skills Radar (the skills this set actually
 * assesses, in S1–S7 order), the flagged-and-never-revisited question ids,
 * and per-question timing. Only available once the attempt is terminal
 * (submitted/timed_out).
 */
export type DiagnosticReportResponse = {
    attempt: DiagnosticAttemptResponse;
    /**
     * Subject
     */
    subject?: string | null;
    /**
     * Answeredcount
     */
    answeredCount: number;
    /**
     * Skillsradar
     */
    skillsRadar: Array<SkillScore>;
    /**
     * Flaggedneverrevisited
     */
    flaggedNeverRevisited: Array<string>;
    /**
     * Perquestiontime
     */
    perQuestionTime: Array<PerQuestionTime>;
    /**
     * Haspass
     */
    hasPass?: boolean;
    /**
     * Upsell
     */
    upsell?: {
        [key: string]: unknown;
    } | null;
};

/**
 * DiagnosticResponseState
 * Per-question progress so far, for rehydrating the exam screen after
 * a refresh/reconnect (§7) — no is_correct, never populated until the
 * attempt is scored (Stage 5), and even then never sent mid-attempt.
 */
export type DiagnosticResponseState = {
    /**
     * Questionid
     */
    questionId: string;
    /**
     * Questionorderindex
     */
    questionOrderIndex: number;
    /**
     * Selectedoption
     */
    selectedOption?: string | null;
    /**
     * Isflagged
     */
    isFlagged?: boolean;
    /**
     * Viewcount
     */
    viewCount?: number;
};

/**
 * DiagnosticSetPreviewResponse
 * Landing/instructions screen, before an attempt exists (§2) — only
 * what's needed to decide to start, nothing about the questions
 * themselves.
 */
export type DiagnosticSetPreviewResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Timelimitminutes
     */
    timeLimitMinutes: number;
    /**
     * Questioncount
     */
    questionCount: number;
};

/**
 * DiagnosticSetResponse
 */
export type DiagnosticSetResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Timelimitminutes
     */
    timeLimitMinutes: number;
    /**
     * Questionids
     */
    questionIds: Array<string>;
    /**
     * Isfree
     */
    isFree: boolean;
    /**
     * Status
     */
    status: 'draft' | 'published';
    /**
     * Subject
     */
    subject?: string | null;
    /**
     * Createdat
     */
    createdAt: string;
};

/**
 * EditOptionBody
 * One answer option as the editor sends it.
 *
 * is_correct is deliberately absent: the answer is stated once, by
 * correct_option on the question, and derived from it here. Two places to say
 * which option is right is two places to disagree.
 */
export type EditOptionBody = {
    /**
     * Label
     */
    label: string;
    /**
     * Text
     */
    text: string;
    /**
     * Misconception
     */
    misconception?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HintRequest
 */
export type HintRequest = {
    /**
     * Question
     */
    question: string;
    /**
     * Questionid
     */
    questionId: string;
};

/**
 * HintResponse
 */
export type HintResponse = {
    /**
     * Hint
     */
    hint: string;
    /**
     * Level
     */
    level?: number;
};

/**
 * IngestDiagnosticEventsBody
 * One call per client-side flush (every few seconds, or on
 * navigation) — not one call per event (§4).
 */
export type IngestDiagnosticEventsBody = {
    /**
     * Events
     */
    events: Array<DiagnosticQuestionEvent>;
};

/**
 * IngestDiagnosticEventsResponse
 */
export type IngestDiagnosticEventsResponse = {
    /**
     * Acceptedcount
     */
    acceptedCount: number;
};

/**
 * LevelWithSyllabus
 */
export type LevelWithSyllabus = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    syllabus: BaseSyllabus;
};

/**
 * OptionResponse
 */
export type OptionResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Questionid
     */
    questionId: string;
    /**
     * Value
     */
    value: string;
    /**
     * Iscorrect
     */
    isCorrect: boolean;
    /**
     * Position
     */
    position: number;
    /**
     * Label
     */
    label?: string | null;
    /**
     * Misconception
     */
    misconception?: string | null;
};

/**
 * PaginatedQuestionResponse
 */
export type PaginatedQuestionResponse = {
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Size
     */
    size: number;
    /**
     * Items
     */
    items: Array<QuestionResponse>;
};

/**
 * Paper
 */
export type Paper = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
};

/**
 * PaperInstance
 */
export type PaperInstance = {
    /**
     * Id
     */
    id: string;
    paper: Paper;
    variant: PaperVariant;
};

/**
 * PaperVariant
 */
export type PaperVariant = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Year
     */
    year: number;
};

/**
 * PerQuestionTime
 * Pacing data for one question: engaged seconds and how many times the
 * student navigated (back) to it — two distinct pacing signals (§6). Read
 * in question_order_index order, this list is the pacing curve.
 */
export type PerQuestionTime = {
    /**
     * Questionid
     */
    questionId: string;
    /**
     * Questionorderindex
     */
    questionOrderIndex: number;
    /**
     * Totaltimeseconds
     */
    totalTimeSeconds: number;
    /**
     * Viewcount
     */
    viewCount: number;
};

/**
 * PublishedDiagnosticSet
 * One published set on the public diagnostics listing — enough to show a
 * card and link through to its start screen. Public (no auth), so it carries
 * no question ids or other internals, only published sets are returned.
 */
export type PublishedDiagnosticSet = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Subject
     */
    subject?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Timelimitminutes
     */
    timeLimitMinutes: number;
    /**
     * Questioncount
     */
    questionCount: number;
    /**
     * Isfree
     */
    isFree: boolean;
};

/**
 * PublishedSubject
 * A subject as the student-facing catalogue needs it — enough for a card,
 * without the full topic and paper lists the admin view carries.
 */
export type PublishedSubject = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Code
     */
    code: string;
    /**
     * Topiccount
     */
    topicCount: number;
    /**
     * Questioncount
     */
    questionCount: number;
};

/**
 * QuestionResponse
 */
export type QuestionResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Difficulty
     */
    difficulty: string;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Topics
     */
    topics: Array<BaseTopic>;
    /**
     * Marks
     */
    marks: number | null;
    /**
     * Status
     */
    status?: 'COMPLETED' | 'NONE' | null;
    /**
     * Type
     */
    type: 'default' | 'multiple_choice';
    /**
     * Questionurl
     */
    questionUrl?: string | null;
    /**
     * Answerurl
     */
    answerUrl?: string | null;
    paper?: Paper | null;
    paperVariant?: PaperVariant | null;
    /**
     * Number
     */
    number?: number | null;
    /**
     * Stem
     */
    stem?: string | null;
    /**
     * Correctoption
     */
    correctOption?: string | null;
    /**
     * Diagramurl
     */
    diagramUrl?: string | null;
    /**
     * Chapter
     */
    chapter?: string | null;
    /**
     * Chaptertitle
     */
    chapterTitle?: string | null;
    /**
     * Topiccode
     */
    topicCode?: string | null;
    /**
     * Archetype
     */
    archetype?: string | null;
    /**
     * Sourceref
     */
    sourceRef?: string | null;
    /**
     * Publishstatus
     */
    publishStatus?: 'draft' | 'published' | null;
};

/**
 * SetCompletionResponse
 */
export type SetCompletionResponse = {
    /**
     * Issuccess
     */
    isSuccess: boolean;
    /**
     * Message
     */
    message: string;
};

/**
 * SkillMisconception
 * One wrong answer, narrated. `misconception` is the distractor's own
 * explanation from the import JSON — the reason this option is tempting —
 * which is what turns a wrong tick into something a student can act on.
 */
export type SkillMisconception = {
    /**
     * Questionid
     */
    questionId: string;
    /**
     * Chosenoption
     */
    chosenOption?: string | null;
    /**
     * Correctoption
     */
    correctOption?: string | null;
    /**
     * Misconception
     */
    misconception?: string | null;
};

/**
 * SkillRadarDetail
 * The paid interpretation layer for one skill axis: the score, plus the
 * specific misconceptions behind the wrong answers on that skill.
 */
export type SkillRadarDetail = {
    /**
     * Skill
     */
    skill: string;
    /**
     * Score
     */
    score?: number | null;
    /**
     * Attempted
     */
    attempted: number;
    /**
     * Correct
     */
    correct: number;
    /**
     * Misconceptions
     */
    misconceptions: Array<SkillMisconception>;
};

/**
 * SkillScore
 * One Skills Radar axis, on a primary-skill basis. score = correct /
 * attempted over the questions whose *primary* skill is this one; it is
 * null when attempted == 0 — 'not measured in this set', which the report
 * must show distinctly from a real 0%. attempted/correct are integer counts
 * so the report can show the denominator ('0 of 4') and flag small samples.
 *
 * Skill codes are decoded to full names on the report screen, per subject
 * (frontend diagnosticSkillFrameworks) — not stored here.
 */
export type SkillScore = {
    /**
     * Skill
     */
    skill: string;
    /**
     * Score
     */
    score?: number | null;
    /**
     * Attempted
     */
    attempted?: number;
    /**
     * Correct
     */
    correct?: number;
};

/**
 * SpmBulkImportRequest
 */
export type SpmBulkImportRequest = {
    questionBank: SpmImportBankMeta;
    /**
     * Questions
     */
    questions: Array<SpmImportQuestion>;
    /**
     * Paperinstanceid
     */
    paperInstanceId?: string | null;
    /**
     * Dryrun
     */
    dryRun?: boolean;
};

/**
 * SpmBulkImportResponse
 */
export type SpmBulkImportResponse = {
    /**
     * Issuccess
     */
    isSuccess: boolean;
    /**
     * Message
     */
    message: string;
    /**
     * Dryrun
     */
    dryRun: boolean;
    /**
     * Createdcount
     */
    createdCount: number;
    /**
     * Updatedcount
     */
    updatedCount: number;
    /**
     * Questionids
     */
    questionIds: Array<string>;
    /**
     * Problems
     */
    problems: Array<SpmImportProblem>;
    /**
     * Unknowntopiccodes
     */
    unknownTopicCodes: Array<string>;
    /**
     * Editedsourcerefs
     */
    editedSourceRefs?: Array<string>;
};

/**
 * SpmImportBankMeta
 */
export type SpmImportBankMeta = {
    /**
     * Title
     */
    title: string;
    /**
     * Subject
     */
    subject: string;
    /**
     * Paper
     */
    paper?: string | null;
    /**
     * Language
     */
    language?: string | null;
    /**
     * Questionorder
     */
    questionOrder: Array<string>;
};

/**
 * SpmImportOption
 */
export type SpmImportOption = {
    /**
     * Label
     */
    label: string;
    /**
     * Text
     */
    text: string;
    /**
     * Iscorrect
     */
    isCorrect?: boolean;
    /**
     * Misconception
     */
    misconception?: string | null;
};

/**
 * SpmImportProblem
 */
export type SpmImportProblem = {
    /**
     * Sourceref
     */
    sourceRef: string;
    /**
     * Problem
     */
    problem: string;
};

/**
 * SpmImportQuestion
 */
export type SpmImportQuestion = {
    /**
     * Sourceref
     */
    sourceRef: string;
    /**
     * Chapter
     */
    chapter: string;
    /**
     * Topiccode
     */
    topicCode: string;
    /**
     * Archetype
     */
    archetype?: string | null;
    /**
     * Difficultytag
     */
    difficultyTag?: string | null;
    /**
     * Stem
     */
    stem: string;
    /**
     * Options
     */
    options: Array<SpmImportOption>;
    /**
     * Correctoption
     */
    correctOption: string;
    /**
     * Diagramsvg
     */
    diagramSvg?: string | null;
    /**
     * Status
     */
    status?: 'draft' | 'published';
    /**
     * Marks
     */
    marks?: number | null;
    /**
     * Note
     */
    note?: string | null;
};

/**
 * StartAttemptBody
 */
export type StartAttemptBody = {
    /**
     * Diagnosticsetid
     */
    diagnosticSetId: string;
    /**
     * Agreedtoterms
     */
    agreedToTerms?: boolean;
};

/**
 * StudentDiagnosticOption
 */
export type StudentDiagnosticOption = {
    /**
     * Label
     */
    label: string;
    /**
     * Text
     */
    text: string;
};

/**
 * StudentDiagnosticQuestionResponse
 * The exam-screen view of a question — no correct_option, no
 * per-option is_correct/misconception. Scoring is server-side only
 * (§3); this is what makes sure a client can never see it mid-attempt.
 */
export type StudentDiagnosticQuestionResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Stem
     */
    stem: string;
    /**
     * Options
     */
    options: Array<StudentDiagnosticOption>;
    /**
     * Diagramurl
     */
    diagramUrl?: string | null;
};

/**
 * Syllabus
 */
export type Syllabus = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Code
     */
    code: string;
    /**
     * Levels
     */
    levels: Array<BaseLevel>;
    /**
     * Subjects
     */
    subjects: Array<BaseSubject>;
    /**
     * Papervariants
     */
    paperVariants: Array<PaperVariant>;
};

/**
 * UpdateDiagnosticQuestionBody
 */
export type UpdateDiagnosticQuestionBody = {
    /**
     * Topiccode
     */
    topicCode?: string | null;
    /**
     * Coreskillprimary
     */
    coreSkillPrimary?: string | null;
    /**
     * Coreskillsecondary
     */
    coreSkillSecondary?: string | null;
    /**
     * Stem
     */
    stem?: string | null;
    /**
     * Options
     */
    options?: Array<DiagnosticOption> | null;
    /**
     * Correctoption
     */
    correctOption?: string | null;
    /**
     * Difficultytag
     */
    difficultyTag?: string | null;
    /**
     * Status
     */
    status?: 'draft' | 'published' | null;
    /**
     * Diagramsvg
     */
    diagramSvg?: string | null;
};

/**
 * UpdateDiagnosticSetBody
 */
export type UpdateDiagnosticSetBody = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Timelimitminutes
     */
    timeLimitMinutes?: number | null;
    /**
     * Isfree
     */
    isFree?: boolean | null;
    /**
     * Status
     */
    status?: 'draft' | 'published' | null;
    /**
     * Subject
     */
    subject?: string | null;
    /**
     * Questionids
     */
    questionIds?: Array<string> | null;
};

/**
 * UpdateOptionBody
 */
export type UpdateOptionBody = {
    /**
     * Value
     */
    value?: string | null;
    /**
     * Iscorrect
     */
    isCorrect?: boolean | null;
};

/**
 * UpdateQuestionBody
 */
export type UpdateQuestionBody = {
    /**
     * Topics
     */
    topics?: Array<string> | null;
    /**
     * Number
     */
    number?: number | null;
    /**
     * Difficulty
     */
    difficulty?: string | null;
    /**
     * Marks
     */
    marks?: number | null;
    /**
     * Stem
     */
    stem?: string | null;
    /**
     * Correctoption
     */
    correctOption?: string | null;
    /**
     * Chapter
     */
    chapter?: string | null;
    /**
     * Topiccode
     */
    topicCode?: string | null;
    /**
     * Archetype
     */
    archetype?: string | null;
    /**
     * Options
     */
    options?: Array<EditOptionBody> | null;
};

/**
 * UpdateSubjectBody
 */
export type UpdateSubjectBody = {
    /**
     * Ispublished
     */
    isPublished?: boolean | null;
};

/**
 * UpdateTopicBody
 * Request body for updating an existing topic. All fields are optional.
 */
export type UpdateTopicBody = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Levelid
     */
    levelId?: string | null;
    /**
     * Sortorder
     */
    sortOrder?: number | null;
};

/**
 * UpsertDiagnosticResponseBody
 * Both fields optional (exclude_unset governs the write, same
 * omit/explicit-null convention as UpdateDiagnosticQuestionBody) so a
 * flag-only toggle doesn't require resending the current answer and
 * vice versa. Deliberately no total_time_seconds or view_count field —
 * both are computed server-side from the event log at submission (§4),
 * never accepted from the client on this endpoint.
 */
export type UpsertDiagnosticResponseBody = {
    /**
     * Selectedoption
     */
    selectedOption?: string | null;
    /**
     * Isflagged
     */
    isFlagged?: boolean | null;
};

/**
 * User
 */
export type User = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Usertype
     */
    userType: 'USER' | 'ADMIN';
};

/**
 * UserLogin
 */
export type UserLogin = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserLoginResponse
 */
export type UserLoginResponse = {
    user: User;
    /**
     * Token
     */
    token: string;
    /**
     * Tokentype
     */
    tokenType?: string;
};

/**
 * UserMoreInfoForm
 */
export type UserMoreInfoForm = {
    /**
     * School
     */
    school: string;
    /**
     * State
     */
    state: 'JOHOR' | 'KEDAH' | 'KELANTAN' | 'KUALA LUMPUR' | 'MELAKA' | 'NEGERI SEMBILAN' | 'PAHANG' | 'PENANG' | 'PERAK' | 'PERLIS' | 'PUTRAJAYA' | 'SABAH' | 'SARAWAK' | 'SELANGOR' | 'TERENGGANU';
    /**
     * Level
     */
    level: string;
};

/**
 * UserMoreInfoResponse
 */
export type UserMoreInfoResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * UserSignup
 */
export type UserSignup = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Name
     */
    name: string;
    /**
     * Category
     */
    category: 'STUDENT' | 'PARENT' | 'TEACHER';
};

/**
 * UserSignupResponse
 */
export type UserSignupResponse = {
    /**
     * Issuccess
     */
    isSuccess: boolean;
    /**
     * Message
     */
    message: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * WaitlistEntry
 */
export type WaitlistEntry = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Product
     */
    product: string;
    /**
     * Createdat
     */
    createdAt: string;
};

/**
 * WaitlistSignupRequest
 */
export type WaitlistSignupRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Product
     */
    product: string;
};

/**
 * WaitlistSignupResponse
 */
export type WaitlistSignupResponse = {
    /**
     * Message
     */
    message: string;
};

export type ConvertLatexConverterPostData = {
    body: BodyConvertLatexConverterPost;
    path?: never;
    query?: never;
    url: '/converter';
};

export type ConvertLatexConverterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConvertLatexConverterPostError = ConvertLatexConverterPostErrors[keyof ConvertLatexConverterPostErrors];

export type ConvertLatexConverterPostResponses = {
    /**
     * Successful Response
     */
    200: ConversionResponse;
};

export type ConvertLatexConverterPostResponse = ConvertLatexConverterPostResponses[keyof ConvertLatexConverterPostResponses];

export type BulkImportSpmQuestionsQuestionsBulkImportPostData = {
    body: SpmBulkImportRequest;
    path?: never;
    query?: never;
    url: '/questions/bulk-import';
};

export type BulkImportSpmQuestionsQuestionsBulkImportPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BulkImportSpmQuestionsQuestionsBulkImportPostError = BulkImportSpmQuestionsQuestionsBulkImportPostErrors[keyof BulkImportSpmQuestionsQuestionsBulkImportPostErrors];

export type BulkImportSpmQuestionsQuestionsBulkImportPostResponses = {
    /**
     * Successful Response
     */
    200: SpmBulkImportResponse;
};

export type BulkImportSpmQuestionsQuestionsBulkImportPostResponse = BulkImportSpmQuestionsQuestionsBulkImportPostResponses[keyof BulkImportSpmQuestionsQuestionsBulkImportPostResponses];

export type GetQuestionsByTopicQuestionsTopicsTopicIdGetData = {
    body?: never;
    path: {
        /**
         * Topic Id
         */
        topic_id: string;
    };
    query?: never;
    url: '/questions/topics/{topic_id}';
};

export type GetQuestionsByTopicQuestionsTopicsTopicIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetQuestionsByTopicQuestionsTopicsTopicIdGetError = GetQuestionsByTopicQuestionsTopicsTopicIdGetErrors[keyof GetQuestionsByTopicQuestionsTopicsTopicIdGetErrors];

export type GetQuestionsByTopicQuestionsTopicsTopicIdGetResponses = {
    /**
     * Response Get Questions By Topic Questions Topics  Topic Id  Get
     * Successful Response
     */
    200: Array<QuestionResponse>;
};

export type GetQuestionsByTopicQuestionsTopicsTopicIdGetResponse = GetQuestionsByTopicQuestionsTopicsTopicIdGetResponses[keyof GetQuestionsByTopicQuestionsTopicsTopicIdGetResponses];

export type GetQuestionsBySubjectPaginatedQuestionsSubjectPaginatedSubjectIdGetData = {
    body?: never;
    path: {
        /**
         * Subject Id
         */
        subject_id: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Size
         */
        size?: number;
        /**
         * Difficulty
         * Filter by difficulty level
         */
        difficulty?: Array<string> | null;
        /**
         * Topics
         * Filter by a list of topic IDs
         */
        topics?: Array<string> | null;
        /**
         * Papers
         * Filter by a list of paper IDs. Paper 1 or Paper 2 for now.
         */
        papers?: Array<string> | null;
        /**
         * Chapters
         * Filter by a list of syllabus chapter codes, e.g. C06.
         */
        chapters?: Array<string> | null;
        /**
         * Status
         * Admin only: 'draft' or 'published'. Ignored for everyone else, who only ever sees published questions.
         */
        status?: string | null;
    };
    url: '/questions/subject/paginated/{subject_id}';
};

export type GetQuestionsBySubjectPaginatedQuestionsSubjectPaginatedSubjectIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetQuestionsBySubjectPaginatedQuestionsSubjectPaginatedSubjectIdGetError = GetQuestionsBySubjectPaginatedQuestionsSubjectPaginatedSubjectIdGetErrors[keyof GetQuestionsBySubjectPaginatedQuestionsSubjectPaginatedSubjectIdGetErrors];

export type GetQuestionsBySubjectPaginatedQuestionsSubjectPaginatedSubjectIdGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedQuestionResponse;
};

export type GetQuestionsBySubjectPaginatedQuestionsSubjectPaginatedSubjectIdGetResponse = GetQuestionsBySubjectPaginatedQuestionsSubjectPaginatedSubjectIdGetResponses[keyof GetQuestionsBySubjectPaginatedQuestionsSubjectPaginatedSubjectIdGetResponses];

export type BulkSetPublishStatusQuestionsBulkStatusPostData = {
    body: BulkPublishBody;
    path?: never;
    query?: never;
    url: '/questions/bulk-status';
};

export type BulkSetPublishStatusQuestionsBulkStatusPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BulkSetPublishStatusQuestionsBulkStatusPostError = BulkSetPublishStatusQuestionsBulkStatusPostErrors[keyof BulkSetPublishStatusQuestionsBulkStatusPostErrors];

export type BulkSetPublishStatusQuestionsBulkStatusPostResponses = {
    /**
     * Successful Response
     */
    200: BulkPublishResponse;
};

export type BulkSetPublishStatusQuestionsBulkStatusPostResponse = BulkSetPublishStatusQuestionsBulkStatusPostResponses[keyof BulkSetPublishStatusQuestionsBulkStatusPostResponses];

export type SetQuestionStatusQuestionsSetStatusPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Question Id
         */
        question_id: string;
        /**
         * Is Completed
         */
        is_completed: boolean;
    };
    url: '/questions/set-status';
};

export type SetQuestionStatusQuestionsSetStatusPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetQuestionStatusQuestionsSetStatusPostError = SetQuestionStatusQuestionsSetStatusPostErrors[keyof SetQuestionStatusQuestionsSetStatusPostErrors];

export type SetQuestionStatusQuestionsSetStatusPostResponses = {
    /**
     * Successful Response
     */
    200: SetCompletionResponse;
};

export type SetQuestionStatusQuestionsSetStatusPostResponse = SetQuestionStatusQuestionsSetStatusPostResponses[keyof SetQuestionStatusQuestionsSetStatusPostResponses];

export type DeleteQuestionQuestionsQuestionIdDeleteData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/questions/{question_id}';
};

export type DeleteQuestionQuestionsQuestionIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteQuestionQuestionsQuestionIdDeleteError = DeleteQuestionQuestionsQuestionIdDeleteErrors[keyof DeleteQuestionQuestionsQuestionIdDeleteErrors];

export type DeleteQuestionQuestionsQuestionIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetQuestionQuestionsQuestionIdGetData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/questions/{question_id}';
};

export type GetQuestionQuestionsQuestionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetQuestionQuestionsQuestionIdGetError = GetQuestionQuestionsQuestionIdGetErrors[keyof GetQuestionQuestionsQuestionIdGetErrors];

export type GetQuestionQuestionsQuestionIdGetResponses = {
    /**
     * Successful Response
     */
    200: QuestionResponse;
};

export type GetQuestionQuestionsQuestionIdGetResponse = GetQuestionQuestionsQuestionIdGetResponses[keyof GetQuestionQuestionsQuestionIdGetResponses];

export type UpdateQuestionQuestionsQuestionIdPatchData = {
    body: UpdateQuestionBody;
    path: {
        /**
         * The ID of the question to update.
         */
        question_id: string;
    };
    query?: never;
    url: '/questions/{question_id}';
};

export type UpdateQuestionQuestionsQuestionIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateQuestionQuestionsQuestionIdPatchError = UpdateQuestionQuestionsQuestionIdPatchErrors[keyof UpdateQuestionQuestionsQuestionIdPatchErrors];

export type UpdateQuestionQuestionsQuestionIdPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetQuestionsByPaperInstanceQuestionsPaperInstancePaperInstanceIdGetData = {
    body?: never;
    path: {
        /**
         * Paper Instance Id
         */
        paper_instance_id: string;
    };
    query?: never;
    url: '/questions/paper_instance/{paper_instance_id}';
};

export type GetQuestionsByPaperInstanceQuestionsPaperInstancePaperInstanceIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetQuestionsByPaperInstanceQuestionsPaperInstancePaperInstanceIdGetError = GetQuestionsByPaperInstanceQuestionsPaperInstancePaperInstanceIdGetErrors[keyof GetQuestionsByPaperInstanceQuestionsPaperInstancePaperInstanceIdGetErrors];

export type GetQuestionsByPaperInstanceQuestionsPaperInstancePaperInstanceIdGetResponses = {
    /**
     * Response Get Questions By Paper Instance Questions Paper Instance  Paper Instance Id  Get
     * Successful Response
     */
    200: Array<QuestionResponse>;
};

export type GetQuestionsByPaperInstanceQuestionsPaperInstancePaperInstanceIdGetResponse = GetQuestionsByPaperInstanceQuestionsPaperInstancePaperInstanceIdGetResponses[keyof GetQuestionsByPaperInstanceQuestionsPaperInstancePaperInstanceIdGetResponses];

export type GetQuestionOptionsQuestionsQuestionIdOptionsGetData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/questions/{question_id}/options';
};

export type GetQuestionOptionsQuestionsQuestionIdOptionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetQuestionOptionsQuestionsQuestionIdOptionsGetError = GetQuestionOptionsQuestionsQuestionIdOptionsGetErrors[keyof GetQuestionOptionsQuestionsQuestionIdOptionsGetErrors];

export type GetQuestionOptionsQuestionsQuestionIdOptionsGetResponses = {
    /**
     * Response Get Question Options Questions  Question Id  Options Get
     * Successful Response
     */
    200: Array<OptionResponse>;
};

export type GetQuestionOptionsQuestionsQuestionIdOptionsGetResponse = GetQuestionOptionsQuestionsQuestionIdOptionsGetResponses[keyof GetQuestionOptionsQuestionsQuestionIdOptionsGetResponses];

export type CreateOptionQuestionsQuestionIdOptionPostData = {
    body: CreateOptionBody;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/questions/{question_id}/option';
};

export type CreateOptionQuestionsQuestionIdOptionPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateOptionQuestionsQuestionIdOptionPostError = CreateOptionQuestionsQuestionIdOptionPostErrors[keyof CreateOptionQuestionsQuestionIdOptionPostErrors];

export type CreateOptionQuestionsQuestionIdOptionPostResponses = {
    /**
     * Successful Response
     */
    200: OptionResponse;
};

export type CreateOptionQuestionsQuestionIdOptionPostResponse = CreateOptionQuestionsQuestionIdOptionPostResponses[keyof CreateOptionQuestionsQuestionIdOptionPostResponses];

export type DeleteOptionQuestionsQuestionIdOptionOptionIdDeleteData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: string;
        /**
         * Option Id
         */
        option_id: string;
    };
    query?: never;
    url: '/questions/{question_id}/option/{option_id}';
};

export type DeleteOptionQuestionsQuestionIdOptionOptionIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteOptionQuestionsQuestionIdOptionOptionIdDeleteError = DeleteOptionQuestionsQuestionIdOptionOptionIdDeleteErrors[keyof DeleteOptionQuestionsQuestionIdOptionOptionIdDeleteErrors];

export type DeleteOptionQuestionsQuestionIdOptionOptionIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: OptionResponse;
};

export type DeleteOptionQuestionsQuestionIdOptionOptionIdDeleteResponse = DeleteOptionQuestionsQuestionIdOptionOptionIdDeleteResponses[keyof DeleteOptionQuestionsQuestionIdOptionOptionIdDeleteResponses];

export type UpdateOptionQuestionsQuestionIdOptionOptionIdPatchData = {
    body: UpdateOptionBody;
    path: {
        /**
         * Question Id
         */
        question_id: string;
        /**
         * Option Id
         */
        option_id: string;
    };
    query?: never;
    url: '/questions/{question_id}/option/{option_id}';
};

export type UpdateOptionQuestionsQuestionIdOptionOptionIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateOptionQuestionsQuestionIdOptionOptionIdPatchError = UpdateOptionQuestionsQuestionIdOptionOptionIdPatchErrors[keyof UpdateOptionQuestionsQuestionIdOptionOptionIdPatchErrors];

export type UpdateOptionQuestionsQuestionIdOptionOptionIdPatchResponses = {
    /**
     * Successful Response
     */
    200: OptionResponse;
};

export type UpdateOptionQuestionsQuestionIdOptionOptionIdPatchResponse = UpdateOptionQuestionsQuestionIdOptionOptionIdPatchResponses[keyof UpdateOptionQuestionsQuestionIdOptionOptionIdPatchResponses];

export type GetAllSyllabusSyllabusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/syllabus';
};

export type GetAllSyllabusSyllabusGetResponses = {
    /**
     * Response Get All Syllabus Syllabus Get
     * Successful Response
     */
    200: Array<Syllabus>;
};

export type GetAllSyllabusSyllabusGetResponse = GetAllSyllabusSyllabusGetResponses[keyof GetAllSyllabusSyllabusGetResponses];

export type CreateSyllabusSyllabusPostData = {
    body: CreateSyllabusBody;
    path?: never;
    query?: never;
    url: '/syllabus';
};

export type CreateSyllabusSyllabusPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSyllabusSyllabusPostError = CreateSyllabusSyllabusPostErrors[keyof CreateSyllabusSyllabusPostErrors];

export type CreateSyllabusSyllabusPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSyllabusSyllabusSyllabusIdGetData = {
    body?: never;
    path: {
        /**
         * Syllabus Id
         */
        syllabus_id: string;
    };
    query?: never;
    url: '/syllabus/{syllabus_id}';
};

export type GetSyllabusSyllabusSyllabusIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSyllabusSyllabusSyllabusIdGetError = GetSyllabusSyllabusSyllabusIdGetErrors[keyof GetSyllabusSyllabusSyllabusIdGetErrors];

export type GetSyllabusSyllabusSyllabusIdGetResponses = {
    /**
     * Successful Response
     */
    200: Syllabus;
};

export type GetSyllabusSyllabusSyllabusIdGetResponse = GetSyllabusSyllabusSyllabusIdGetResponses[keyof GetSyllabusSyllabusSyllabusIdGetResponses];

export type ListPublishedSubjectsSubjectsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/subjects';
};

export type ListPublishedSubjectsSubjectsGetResponses = {
    /**
     * Response List Published Subjects Subjects Get
     * Successful Response
     */
    200: Array<PublishedSubject>;
};

export type ListPublishedSubjectsSubjectsGetResponse = ListPublishedSubjectsSubjectsGetResponses[keyof ListPublishedSubjectsSubjectsGetResponses];

export type CreateSubjectSubjectsPostData = {
    body: CreateSubjectBody;
    path?: never;
    query?: never;
    url: '/subjects';
};

export type CreateSubjectSubjectsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSubjectSubjectsPostError = CreateSubjectSubjectsPostErrors[keyof CreateSubjectSubjectsPostErrors];

export type CreateSubjectSubjectsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSubjectSubjectsSubjectIdGetData = {
    body?: never;
    path: {
        /**
         * Subject Id
         */
        subject_id: string;
    };
    query?: never;
    url: '/subjects/{subject_id}';
};

export type GetSubjectSubjectsSubjectIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSubjectSubjectsSubjectIdGetError = GetSubjectSubjectsSubjectIdGetErrors[keyof GetSubjectSubjectsSubjectIdGetErrors];

export type GetSubjectSubjectsSubjectIdGetResponses = {
    /**
     * Successful Response
     */
    200: BaseSubject;
};

export type GetSubjectSubjectsSubjectIdGetResponse = GetSubjectSubjectsSubjectIdGetResponses[keyof GetSubjectSubjectsSubjectIdGetResponses];

export type UpdateSubjectSubjectsSubjectIdPatchData = {
    body: UpdateSubjectBody;
    path: {
        /**
         * Subject Id
         */
        subject_id: string;
    };
    query?: never;
    url: '/subjects/{subject_id}';
};

export type UpdateSubjectSubjectsSubjectIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSubjectSubjectsSubjectIdPatchError = UpdateSubjectSubjectsSubjectIdPatchErrors[keyof UpdateSubjectSubjectsSubjectIdPatchErrors];

export type UpdateSubjectSubjectsSubjectIdPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAllLevelsLevelsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/levels';
};

export type GetAllLevelsLevelsGetResponses = {
    /**
     * Response Get All Levels Levels Get
     * Successful Response
     */
    200: Array<LevelWithSyllabus>;
};

export type GetAllLevelsLevelsGetResponse = GetAllLevelsLevelsGetResponses[keyof GetAllLevelsLevelsGetResponses];

export type CreateLevelLevelsPostData = {
    body: CreateLevelBody;
    path?: never;
    query?: never;
    url: '/levels';
};

export type CreateLevelLevelsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateLevelLevelsPostError = CreateLevelLevelsPostErrors[keyof CreateLevelLevelsPostErrors];

export type CreateLevelLevelsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteLevelLevelsLevelIdDeleteData = {
    body?: never;
    path: {
        /**
         * Level Id
         */
        level_id: string;
    };
    query?: never;
    url: '/levels/{level_id}';
};

export type DeleteLevelLevelsLevelIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteLevelLevelsLevelIdDeleteError = DeleteLevelLevelsLevelIdDeleteErrors[keyof DeleteLevelLevelsLevelIdDeleteErrors];

export type DeleteLevelLevelsLevelIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetTopicsBySubjectTopicsSubjectIdGetData = {
    body?: never;
    path: {
        /**
         * Subject Id
         */
        subject_id: string;
    };
    query?: never;
    url: '/topics/{subject_id}';
};

export type GetTopicsBySubjectTopicsSubjectIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTopicsBySubjectTopicsSubjectIdGetError = GetTopicsBySubjectTopicsSubjectIdGetErrors[keyof GetTopicsBySubjectTopicsSubjectIdGetErrors];

export type GetTopicsBySubjectTopicsSubjectIdGetResponses = {
    /**
     * Response Get Topics By Subject Topics  Subject Id  Get
     * Successful Response
     */
    200: Array<BaseTopic>;
};

export type GetTopicsBySubjectTopicsSubjectIdGetResponse = GetTopicsBySubjectTopicsSubjectIdGetResponses[keyof GetTopicsBySubjectTopicsSubjectIdGetResponses];

export type CreateTopicTopicsPostData = {
    body: CreateTopicBody;
    path?: never;
    query?: never;
    url: '/topics';
};

export type CreateTopicTopicsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTopicTopicsPostError = CreateTopicTopicsPostErrors[keyof CreateTopicTopicsPostErrors];

export type CreateTopicTopicsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteTopicTopicsTopicIdDeleteData = {
    body?: never;
    path: {
        /**
         * Topic Id
         */
        topic_id: string;
    };
    query?: never;
    url: '/topics/{topic_id}';
};

export type DeleteTopicTopicsTopicIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTopicTopicsTopicIdDeleteError = DeleteTopicTopicsTopicIdDeleteErrors[keyof DeleteTopicTopicsTopicIdDeleteErrors];

export type DeleteTopicTopicsTopicIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateTopicTopicsTopicIdPatchData = {
    body: UpdateTopicBody;
    path: {
        /**
         * Topic Id
         */
        topic_id: string;
    };
    query?: never;
    url: '/topics/{topic_id}';
};

export type UpdateTopicTopicsTopicIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTopicTopicsTopicIdPatchError = UpdateTopicTopicsTopicIdPatchErrors[keyof UpdateTopicTopicsTopicIdPatchErrors];

export type UpdateTopicTopicsTopicIdPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreatePaperPapersPostData = {
    body: CreatePaperBody;
    path?: never;
    query?: never;
    url: '/papers';
};

export type CreatePaperPapersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePaperPapersPostError = CreatePaperPapersPostErrors[keyof CreatePaperPapersPostErrors];

export type CreatePaperPapersPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeletePaperPapersPaperIdDeleteData = {
    body?: never;
    path: {
        /**
         * Paper Id
         */
        paper_id: string;
    };
    query?: never;
    url: '/papers/{paper_id}';
};

export type DeletePaperPapersPaperIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePaperPapersPaperIdDeleteError = DeletePaperPapersPaperIdDeleteErrors[keyof DeletePaperPapersPaperIdDeleteErrors];

export type DeletePaperPapersPaperIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeletePaperInstancePapersInstanceInstanceIdDeleteData = {
    body?: never;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
    };
    query?: never;
    url: '/papers/instance/{instance_id}';
};

export type DeletePaperInstancePapersInstanceInstanceIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePaperInstancePapersInstanceInstanceIdDeleteError = DeletePaperInstancePapersInstanceInstanceIdDeleteErrors[keyof DeletePaperInstancePapersInstanceInstanceIdDeleteErrors];

export type DeletePaperInstancePapersInstanceInstanceIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPaperInstancePapersInstanceInstanceIdGetData = {
    body?: never;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
    };
    query?: never;
    url: '/papers/instance/{instance_id}';
};

export type GetPaperInstancePapersInstanceInstanceIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPaperInstancePapersInstanceInstanceIdGetError = GetPaperInstancePapersInstanceInstanceIdGetErrors[keyof GetPaperInstancePapersInstanceInstanceIdGetErrors];

export type GetPaperInstancePapersInstanceInstanceIdGetResponses = {
    /**
     * Successful Response
     */
    200: PaperInstance;
};

export type GetPaperInstancePapersInstanceInstanceIdGetResponse = GetPaperInstancePapersInstanceInstanceIdGetResponses[keyof GetPaperInstancePapersInstanceInstanceIdGetResponses];

export type GetPaperInstancesBySubjectIdPapersInstanceSubjectSubjectIdGetData = {
    body?: never;
    path: {
        /**
         * Subject Id
         */
        subject_id: string;
    };
    query?: never;
    url: '/papers/instance/subject/{subject_id}';
};

export type GetPaperInstancesBySubjectIdPapersInstanceSubjectSubjectIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPaperInstancesBySubjectIdPapersInstanceSubjectSubjectIdGetError = GetPaperInstancesBySubjectIdPapersInstanceSubjectSubjectIdGetErrors[keyof GetPaperInstancesBySubjectIdPapersInstanceSubjectSubjectIdGetErrors];

export type GetPaperInstancesBySubjectIdPapersInstanceSubjectSubjectIdGetResponses = {
    /**
     * Response Get Paper Instances By Subject Id Papers Instance Subject  Subject Id  Get
     * Successful Response
     */
    200: Array<PaperInstance>;
};

export type GetPaperInstancesBySubjectIdPapersInstanceSubjectSubjectIdGetResponse = GetPaperInstancesBySubjectIdPapersInstanceSubjectSubjectIdGetResponses[keyof GetPaperInstancesBySubjectIdPapersInstanceSubjectSubjectIdGetResponses];

export type CreatePaperInstancePapersInstancePostData = {
    body: CreatePaperInstanceBody;
    path?: never;
    query?: never;
    url: '/papers/instance';
};

export type CreatePaperInstancePapersInstancePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePaperInstancePapersInstancePostError = CreatePaperInstancePapersInstancePostErrors[keyof CreatePaperInstancePapersInstancePostErrors];

export type CreatePaperInstancePapersInstancePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreatePaperVariantPapersVariantPostData = {
    body: CreatePaperVariantBody;
    path?: never;
    query?: never;
    url: '/papers/variant';
};

export type CreatePaperVariantPapersVariantPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePaperVariantPapersVariantPostError = CreatePaperVariantPapersVariantPostErrors[keyof CreatePaperVariantPapersVariantPostErrors];

export type CreatePaperVariantPapersVariantPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteVariantPapersVariantVariantIdDeleteData = {
    body?: never;
    path: {
        /**
         * Variant Id
         */
        variant_id: string;
    };
    query?: never;
    url: '/papers/variant/{variant_id}';
};

export type DeleteVariantPapersVariantVariantIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteVariantPapersVariantVariantIdDeleteError = DeleteVariantPapersVariantVariantIdDeleteErrors[keyof DeleteVariantPapersVariantVariantIdDeleteErrors];

export type DeleteVariantPapersVariantVariantIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SignupUsersPostData = {
    body: UserSignup;
    path?: never;
    query?: never;
    url: '/users';
};

export type SignupUsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SignupUsersPostError = SignupUsersPostErrors[keyof SignupUsersPostErrors];

export type SignupUsersPostResponses = {
    /**
     * Successful Response
     */
    200: UserSignupResponse;
};

export type SignupUsersPostResponse = SignupUsersPostResponses[keyof SignupUsersPostResponses];

export type LoginUsersLoginPostData = {
    body: UserLogin;
    path?: never;
    query?: never;
    url: '/users/login';
};

export type LoginUsersLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginUsersLoginPostError = LoginUsersLoginPostErrors[keyof LoginUsersLoginPostErrors];

export type LoginUsersLoginPostResponses = {
    /**
     * Successful Response
     */
    200: UserLoginResponse;
};

export type LoginUsersLoginPostResponse = LoginUsersLoginPostResponses[keyof LoginUsersLoginPostResponses];

export type VerifyEmailUsersVerifyPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Token
         */
        token: string;
    };
    url: '/users/verify';
};

export type VerifyEmailUsersVerifyPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerifyEmailUsersVerifyPostError = VerifyEmailUsersVerifyPostErrors[keyof VerifyEmailUsersVerifyPostErrors];

export type VerifyEmailUsersVerifyPostResponses = {
    /**
     * Successful Response
     */
    200: AccountVerificationResponse;
};

export type VerifyEmailUsersVerifyPostResponse = VerifyEmailUsersVerifyPostResponses[keyof VerifyEmailUsersVerifyPostResponses];

export type ResendVerificationUsersResendVerificationPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email
         */
        email: string;
    };
    url: '/users/resend-verification';
};

export type ResendVerificationUsersResendVerificationPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResendVerificationUsersResendVerificationPostError = ResendVerificationUsersResendVerificationPostErrors[keyof ResendVerificationUsersResendVerificationPostErrors];

export type ResendVerificationUsersResendVerificationPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type MoreInfoUsersMoreInfoPostData = {
    body: UserMoreInfoForm;
    path?: never;
    query?: never;
    url: '/users/more-info';
};

export type MoreInfoUsersMoreInfoPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MoreInfoUsersMoreInfoPostError = MoreInfoUsersMoreInfoPostErrors[keyof MoreInfoUsersMoreInfoPostErrors];

export type MoreInfoUsersMoreInfoPostResponses = {
    /**
     * Successful Response
     */
    200: UserMoreInfoResponse;
};

export type MoreInfoUsersMoreInfoPostResponse = MoreInfoUsersMoreInfoPostResponses[keyof MoreInfoUsersMoreInfoPostResponses];

export type GetCurrentUserUsersCurrentGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/current';
};

export type GetCurrentUserUsersCurrentGetResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type GetCurrentUserUsersCurrentGetResponse = GetCurrentUserUsersCurrentGetResponses[keyof GetCurrentUserUsersCurrentGetResponses];

export type GetHintChatHintPostData = {
    body: HintRequest;
    path?: never;
    query?: never;
    url: '/chat/hint';
};

export type GetHintChatHintPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetHintChatHintPostError = GetHintChatHintPostErrors[keyof GetHintChatHintPostErrors];

export type GetHintChatHintPostResponses = {
    /**
     * Successful Response
     */
    200: HintResponse;
};

export type GetHintChatHintPostResponse = GetHintChatHintPostResponses[keyof GetHintChatHintPostResponses];

export type ListDiagnosticQuestionsDiagnosticQuestionsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Status
         */
        status?: 'draft' | 'published' | null;
        /**
         * Topic Code
         */
        topic_code?: string | null;
    };
    url: '/diagnostic/questions';
};

export type ListDiagnosticQuestionsDiagnosticQuestionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListDiagnosticQuestionsDiagnosticQuestionsGetError = ListDiagnosticQuestionsDiagnosticQuestionsGetErrors[keyof ListDiagnosticQuestionsDiagnosticQuestionsGetErrors];

export type ListDiagnosticQuestionsDiagnosticQuestionsGetResponses = {
    /**
     * Response List Diagnostic Questions Diagnostic Questions Get
     * Successful Response
     */
    200: Array<DiagnosticQuestionResponse>;
};

export type ListDiagnosticQuestionsDiagnosticQuestionsGetResponse = ListDiagnosticQuestionsDiagnosticQuestionsGetResponses[keyof ListDiagnosticQuestionsDiagnosticQuestionsGetResponses];

export type CreateDiagnosticQuestionDiagnosticQuestionsPostData = {
    body: CreateDiagnosticQuestionBody;
    path?: never;
    query?: never;
    url: '/diagnostic/questions';
};

export type CreateDiagnosticQuestionDiagnosticQuestionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateDiagnosticQuestionDiagnosticQuestionsPostError = CreateDiagnosticQuestionDiagnosticQuestionsPostErrors[keyof CreateDiagnosticQuestionDiagnosticQuestionsPostErrors];

export type CreateDiagnosticQuestionDiagnosticQuestionsPostResponses = {
    /**
     * Successful Response
     */
    200: DiagnosticQuestionResponse;
};

export type CreateDiagnosticQuestionDiagnosticQuestionsPostResponse = CreateDiagnosticQuestionDiagnosticQuestionsPostResponses[keyof CreateDiagnosticQuestionDiagnosticQuestionsPostResponses];

export type BulkSetQuestionStatusDiagnosticQuestionsBulkStatusPostData = {
    body: BulkQuestionStatusBody;
    path?: never;
    query?: never;
    url: '/diagnostic/questions/bulk-status';
};

export type BulkSetQuestionStatusDiagnosticQuestionsBulkStatusPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BulkSetQuestionStatusDiagnosticQuestionsBulkStatusPostError = BulkSetQuestionStatusDiagnosticQuestionsBulkStatusPostErrors[keyof BulkSetQuestionStatusDiagnosticQuestionsBulkStatusPostErrors];

export type BulkSetQuestionStatusDiagnosticQuestionsBulkStatusPostResponses = {
    /**
     * Successful Response
     */
    200: BulkQuestionStatusResponse;
};

export type BulkSetQuestionStatusDiagnosticQuestionsBulkStatusPostResponse = BulkSetQuestionStatusDiagnosticQuestionsBulkStatusPostResponses[keyof BulkSetQuestionStatusDiagnosticQuestionsBulkStatusPostResponses];

export type DeleteDiagnosticQuestionDiagnosticQuestionsQuestionIdDeleteData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/diagnostic/questions/{question_id}';
};

export type DeleteDiagnosticQuestionDiagnosticQuestionsQuestionIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteDiagnosticQuestionDiagnosticQuestionsQuestionIdDeleteError = DeleteDiagnosticQuestionDiagnosticQuestionsQuestionIdDeleteErrors[keyof DeleteDiagnosticQuestionDiagnosticQuestionsQuestionIdDeleteErrors];

export type DeleteDiagnosticQuestionDiagnosticQuestionsQuestionIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetDiagnosticQuestionDiagnosticQuestionsQuestionIdGetData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/diagnostic/questions/{question_id}';
};

export type GetDiagnosticQuestionDiagnosticQuestionsQuestionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDiagnosticQuestionDiagnosticQuestionsQuestionIdGetError = GetDiagnosticQuestionDiagnosticQuestionsQuestionIdGetErrors[keyof GetDiagnosticQuestionDiagnosticQuestionsQuestionIdGetErrors];

export type GetDiagnosticQuestionDiagnosticQuestionsQuestionIdGetResponses = {
    /**
     * Successful Response
     */
    200: DiagnosticQuestionResponse;
};

export type GetDiagnosticQuestionDiagnosticQuestionsQuestionIdGetResponse = GetDiagnosticQuestionDiagnosticQuestionsQuestionIdGetResponses[keyof GetDiagnosticQuestionDiagnosticQuestionsQuestionIdGetResponses];

export type UpdateDiagnosticQuestionDiagnosticQuestionsQuestionIdPatchData = {
    body: UpdateDiagnosticQuestionBody;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/diagnostic/questions/{question_id}';
};

export type UpdateDiagnosticQuestionDiagnosticQuestionsQuestionIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateDiagnosticQuestionDiagnosticQuestionsQuestionIdPatchError = UpdateDiagnosticQuestionDiagnosticQuestionsQuestionIdPatchErrors[keyof UpdateDiagnosticQuestionDiagnosticQuestionsQuestionIdPatchErrors];

export type UpdateDiagnosticQuestionDiagnosticQuestionsQuestionIdPatchResponses = {
    /**
     * Successful Response
     */
    200: DiagnosticQuestionResponse;
};

export type UpdateDiagnosticQuestionDiagnosticQuestionsQuestionIdPatchResponse = UpdateDiagnosticQuestionDiagnosticQuestionsQuestionIdPatchResponses[keyof UpdateDiagnosticQuestionDiagnosticQuestionsQuestionIdPatchResponses];

export type UploadDiagnosticQuestionDiagramDiagnosticQuestionsQuestionIdDiagramPostData = {
    body: BodyUploadDiagnosticQuestionDiagramDiagnosticQuestionsQuestionIdDiagramPost;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/diagnostic/questions/{question_id}/diagram';
};

export type UploadDiagnosticQuestionDiagramDiagnosticQuestionsQuestionIdDiagramPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadDiagnosticQuestionDiagramDiagnosticQuestionsQuestionIdDiagramPostError = UploadDiagnosticQuestionDiagramDiagnosticQuestionsQuestionIdDiagramPostErrors[keyof UploadDiagnosticQuestionDiagramDiagnosticQuestionsQuestionIdDiagramPostErrors];

export type UploadDiagnosticQuestionDiagramDiagnosticQuestionsQuestionIdDiagramPostResponses = {
    /**
     * Successful Response
     */
    200: DiagnosticQuestionResponse;
};

export type UploadDiagnosticQuestionDiagramDiagnosticQuestionsQuestionIdDiagramPostResponse = UploadDiagnosticQuestionDiagramDiagnosticQuestionsQuestionIdDiagramPostResponses[keyof UploadDiagnosticQuestionDiagramDiagnosticQuestionsQuestionIdDiagramPostResponses];

export type BulkImportDiagnosticQuestionsDiagnosticQuestionsBulkImportPostData = {
    body: BulkImportRequest;
    path?: never;
    query?: never;
    url: '/diagnostic/questions/bulk-import';
};

export type BulkImportDiagnosticQuestionsDiagnosticQuestionsBulkImportPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BulkImportDiagnosticQuestionsDiagnosticQuestionsBulkImportPostError = BulkImportDiagnosticQuestionsDiagnosticQuestionsBulkImportPostErrors[keyof BulkImportDiagnosticQuestionsDiagnosticQuestionsBulkImportPostErrors];

export type BulkImportDiagnosticQuestionsDiagnosticQuestionsBulkImportPostResponses = {
    /**
     * Successful Response
     */
    200: BulkImportResponse;
};

export type BulkImportDiagnosticQuestionsDiagnosticQuestionsBulkImportPostResponse = BulkImportDiagnosticQuestionsDiagnosticQuestionsBulkImportPostResponses[keyof BulkImportDiagnosticQuestionsDiagnosticQuestionsBulkImportPostResponses];

export type ListDiagnosticSetsDiagnosticSetsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Status
         */
        status?: 'draft' | 'published' | null;
    };
    url: '/diagnostic/sets';
};

export type ListDiagnosticSetsDiagnosticSetsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListDiagnosticSetsDiagnosticSetsGetError = ListDiagnosticSetsDiagnosticSetsGetErrors[keyof ListDiagnosticSetsDiagnosticSetsGetErrors];

export type ListDiagnosticSetsDiagnosticSetsGetResponses = {
    /**
     * Response List Diagnostic Sets Diagnostic Sets Get
     * Successful Response
     */
    200: Array<DiagnosticSetResponse>;
};

export type ListDiagnosticSetsDiagnosticSetsGetResponse = ListDiagnosticSetsDiagnosticSetsGetResponses[keyof ListDiagnosticSetsDiagnosticSetsGetResponses];

export type CreateDiagnosticSetDiagnosticSetsPostData = {
    body: CreateDiagnosticSetBody;
    path?: never;
    query?: never;
    url: '/diagnostic/sets';
};

export type CreateDiagnosticSetDiagnosticSetsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateDiagnosticSetDiagnosticSetsPostError = CreateDiagnosticSetDiagnosticSetsPostErrors[keyof CreateDiagnosticSetDiagnosticSetsPostErrors];

export type CreateDiagnosticSetDiagnosticSetsPostResponses = {
    /**
     * Successful Response
     */
    201: DiagnosticSetResponse;
};

export type CreateDiagnosticSetDiagnosticSetsPostResponse = CreateDiagnosticSetDiagnosticSetsPostResponses[keyof CreateDiagnosticSetDiagnosticSetsPostResponses];

export type ListPublishedDiagnosticSetsDiagnosticSetsPublishedGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Test
         */
        test?: string | null;
    };
    url: '/diagnostic/sets/published';
};

export type ListPublishedDiagnosticSetsDiagnosticSetsPublishedGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPublishedDiagnosticSetsDiagnosticSetsPublishedGetError = ListPublishedDiagnosticSetsDiagnosticSetsPublishedGetErrors[keyof ListPublishedDiagnosticSetsDiagnosticSetsPublishedGetErrors];

export type ListPublishedDiagnosticSetsDiagnosticSetsPublishedGetResponses = {
    /**
     * Response List Published Diagnostic Sets Diagnostic Sets Published Get
     * Successful Response
     */
    200: Array<PublishedDiagnosticSet>;
};

export type ListPublishedDiagnosticSetsDiagnosticSetsPublishedGetResponse = ListPublishedDiagnosticSetsDiagnosticSetsPublishedGetResponses[keyof ListPublishedDiagnosticSetsDiagnosticSetsPublishedGetResponses];

export type DeleteDiagnosticSetDiagnosticSetsSetIdDeleteData = {
    body?: never;
    path: {
        /**
         * Set Id
         */
        set_id: string;
    };
    query?: never;
    url: '/diagnostic/sets/{set_id}';
};

export type DeleteDiagnosticSetDiagnosticSetsSetIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteDiagnosticSetDiagnosticSetsSetIdDeleteError = DeleteDiagnosticSetDiagnosticSetsSetIdDeleteErrors[keyof DeleteDiagnosticSetDiagnosticSetsSetIdDeleteErrors];

export type DeleteDiagnosticSetDiagnosticSetsSetIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetDiagnosticSetDiagnosticSetsSetIdGetData = {
    body?: never;
    path: {
        /**
         * Set Id
         */
        set_id: string;
    };
    query?: never;
    url: '/diagnostic/sets/{set_id}';
};

export type GetDiagnosticSetDiagnosticSetsSetIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDiagnosticSetDiagnosticSetsSetIdGetError = GetDiagnosticSetDiagnosticSetsSetIdGetErrors[keyof GetDiagnosticSetDiagnosticSetsSetIdGetErrors];

export type GetDiagnosticSetDiagnosticSetsSetIdGetResponses = {
    /**
     * Successful Response
     */
    200: DiagnosticSetResponse;
};

export type GetDiagnosticSetDiagnosticSetsSetIdGetResponse = GetDiagnosticSetDiagnosticSetsSetIdGetResponses[keyof GetDiagnosticSetDiagnosticSetsSetIdGetResponses];

export type UpdateDiagnosticSetDiagnosticSetsSetIdPatchData = {
    body: UpdateDiagnosticSetBody;
    path: {
        /**
         * Set Id
         */
        set_id: string;
    };
    query?: never;
    url: '/diagnostic/sets/{set_id}';
};

export type UpdateDiagnosticSetDiagnosticSetsSetIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateDiagnosticSetDiagnosticSetsSetIdPatchError = UpdateDiagnosticSetDiagnosticSetsSetIdPatchErrors[keyof UpdateDiagnosticSetDiagnosticSetsSetIdPatchErrors];

export type UpdateDiagnosticSetDiagnosticSetsSetIdPatchResponses = {
    /**
     * Successful Response
     */
    200: DiagnosticSetResponse;
};

export type UpdateDiagnosticSetDiagnosticSetsSetIdPatchResponse = UpdateDiagnosticSetDiagnosticSetsSetIdPatchResponses[keyof UpdateDiagnosticSetDiagnosticSetsSetIdPatchResponses];

export type PreviewDiagnosticSetDiagnosticSetsSetIdPreviewGetData = {
    body?: never;
    path: {
        /**
         * Set Id
         */
        set_id: string;
    };
    query?: never;
    url: '/diagnostic/sets/{set_id}/preview';
};

export type PreviewDiagnosticSetDiagnosticSetsSetIdPreviewGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PreviewDiagnosticSetDiagnosticSetsSetIdPreviewGetError = PreviewDiagnosticSetDiagnosticSetsSetIdPreviewGetErrors[keyof PreviewDiagnosticSetDiagnosticSetsSetIdPreviewGetErrors];

export type PreviewDiagnosticSetDiagnosticSetsSetIdPreviewGetResponses = {
    /**
     * Successful Response
     */
    200: DiagnosticSetPreviewResponse;
};

export type PreviewDiagnosticSetDiagnosticSetsSetIdPreviewGetResponse = PreviewDiagnosticSetDiagnosticSetsSetIdPreviewGetResponses[keyof PreviewDiagnosticSetDiagnosticSetsSetIdPreviewGetResponses];

export type StartOrResumeAttemptDiagnosticAttemptsPostData = {
    body: StartAttemptBody;
    path?: never;
    query?: never;
    url: '/diagnostic/attempts';
};

export type StartOrResumeAttemptDiagnosticAttemptsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartOrResumeAttemptDiagnosticAttemptsPostError = StartOrResumeAttemptDiagnosticAttemptsPostErrors[keyof StartOrResumeAttemptDiagnosticAttemptsPostErrors];

export type StartOrResumeAttemptDiagnosticAttemptsPostResponses = {
    /**
     * Successful Response
     */
    200: DiagnosticAttemptStateResponse;
};

export type StartOrResumeAttemptDiagnosticAttemptsPostResponse = StartOrResumeAttemptDiagnosticAttemptsPostResponses[keyof StartOrResumeAttemptDiagnosticAttemptsPostResponses];

export type GetAttemptStateDiagnosticAttemptsAttemptIdGetData = {
    body?: never;
    path: {
        /**
         * Attempt Id
         */
        attempt_id: string;
    };
    query?: never;
    url: '/diagnostic/attempts/{attempt_id}';
};

export type GetAttemptStateDiagnosticAttemptsAttemptIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAttemptStateDiagnosticAttemptsAttemptIdGetError = GetAttemptStateDiagnosticAttemptsAttemptIdGetErrors[keyof GetAttemptStateDiagnosticAttemptsAttemptIdGetErrors];

export type GetAttemptStateDiagnosticAttemptsAttemptIdGetResponses = {
    /**
     * Successful Response
     */
    200: DiagnosticAttemptStateResponse;
};

export type GetAttemptStateDiagnosticAttemptsAttemptIdGetResponse = GetAttemptStateDiagnosticAttemptsAttemptIdGetResponses[keyof GetAttemptStateDiagnosticAttemptsAttemptIdGetResponses];

export type UpsertDiagnosticResponseDiagnosticAttemptsAttemptIdResponsesQuestionIdPatchData = {
    body: UpsertDiagnosticResponseBody;
    path: {
        /**
         * Attempt Id
         */
        attempt_id: string;
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/diagnostic/attempts/{attempt_id}/responses/{question_id}';
};

export type UpsertDiagnosticResponseDiagnosticAttemptsAttemptIdResponsesQuestionIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpsertDiagnosticResponseDiagnosticAttemptsAttemptIdResponsesQuestionIdPatchError = UpsertDiagnosticResponseDiagnosticAttemptsAttemptIdResponsesQuestionIdPatchErrors[keyof UpsertDiagnosticResponseDiagnosticAttemptsAttemptIdResponsesQuestionIdPatchErrors];

export type UpsertDiagnosticResponseDiagnosticAttemptsAttemptIdResponsesQuestionIdPatchResponses = {
    /**
     * Successful Response
     */
    200: DiagnosticResponseState;
};

export type UpsertDiagnosticResponseDiagnosticAttemptsAttemptIdResponsesQuestionIdPatchResponse = UpsertDiagnosticResponseDiagnosticAttemptsAttemptIdResponsesQuestionIdPatchResponses[keyof UpsertDiagnosticResponseDiagnosticAttemptsAttemptIdResponsesQuestionIdPatchResponses];

export type IngestDiagnosticEventsDiagnosticAttemptsAttemptIdEventsPostData = {
    body: IngestDiagnosticEventsBody;
    path: {
        /**
         * Attempt Id
         */
        attempt_id: string;
    };
    query?: never;
    url: '/diagnostic/attempts/{attempt_id}/events';
};

export type IngestDiagnosticEventsDiagnosticAttemptsAttemptIdEventsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IngestDiagnosticEventsDiagnosticAttemptsAttemptIdEventsPostError = IngestDiagnosticEventsDiagnosticAttemptsAttemptIdEventsPostErrors[keyof IngestDiagnosticEventsDiagnosticAttemptsAttemptIdEventsPostErrors];

export type IngestDiagnosticEventsDiagnosticAttemptsAttemptIdEventsPostResponses = {
    /**
     * Successful Response
     */
    200: IngestDiagnosticEventsResponse;
};

export type IngestDiagnosticEventsDiagnosticAttemptsAttemptIdEventsPostResponse = IngestDiagnosticEventsDiagnosticAttemptsAttemptIdEventsPostResponses[keyof IngestDiagnosticEventsDiagnosticAttemptsAttemptIdEventsPostResponses];

export type SubmitAttemptDiagnosticAttemptsAttemptIdSubmitPostData = {
    body?: never;
    path: {
        /**
         * Attempt Id
         */
        attempt_id: string;
    };
    query?: never;
    url: '/diagnostic/attempts/{attempt_id}/submit';
};

export type SubmitAttemptDiagnosticAttemptsAttemptIdSubmitPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitAttemptDiagnosticAttemptsAttemptIdSubmitPostError = SubmitAttemptDiagnosticAttemptsAttemptIdSubmitPostErrors[keyof SubmitAttemptDiagnosticAttemptsAttemptIdSubmitPostErrors];

export type SubmitAttemptDiagnosticAttemptsAttemptIdSubmitPostResponses = {
    /**
     * Successful Response
     */
    200: DiagnosticAttemptStateResponse;
};

export type SubmitAttemptDiagnosticAttemptsAttemptIdSubmitPostResponse = SubmitAttemptDiagnosticAttemptsAttemptIdSubmitPostResponses[keyof SubmitAttemptDiagnosticAttemptsAttemptIdSubmitPostResponses];

export type GetAttemptReportDiagnosticAttemptsAttemptIdReportGetData = {
    body?: never;
    path: {
        /**
         * Attempt Id
         */
        attempt_id: string;
    };
    query?: never;
    url: '/diagnostic/attempts/{attempt_id}/report';
};

export type GetAttemptReportDiagnosticAttemptsAttemptIdReportGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAttemptReportDiagnosticAttemptsAttemptIdReportGetError = GetAttemptReportDiagnosticAttemptsAttemptIdReportGetErrors[keyof GetAttemptReportDiagnosticAttemptsAttemptIdReportGetErrors];

export type GetAttemptReportDiagnosticAttemptsAttemptIdReportGetResponses = {
    /**
     * Successful Response
     */
    200: DiagnosticReportResponse;
};

export type GetAttemptReportDiagnosticAttemptsAttemptIdReportGetResponse = GetAttemptReportDiagnosticAttemptsAttemptIdReportGetResponses[keyof GetAttemptReportDiagnosticAttemptsAttemptIdReportGetResponses];

export type GetAttemptRadarDiagnosticAttemptsAttemptIdRadarGetData = {
    body?: never;
    path: {
        /**
         * Attempt Id
         */
        attempt_id: string;
    };
    query?: never;
    url: '/diagnostic/attempts/{attempt_id}/radar';
};

export type GetAttemptRadarDiagnosticAttemptsAttemptIdRadarGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAttemptRadarDiagnosticAttemptsAttemptIdRadarGetError = GetAttemptRadarDiagnosticAttemptsAttemptIdRadarGetErrors[keyof GetAttemptRadarDiagnosticAttemptsAttemptIdRadarGetErrors];

export type GetAttemptRadarDiagnosticAttemptsAttemptIdRadarGetResponses = {
    /**
     * Successful Response
     */
    200: AttemptRadarResponse;
};

export type GetAttemptRadarDiagnosticAttemptsAttemptIdRadarGetResponse = GetAttemptRadarDiagnosticAttemptsAttemptIdRadarGetResponses[keyof GetAttemptRadarDiagnosticAttemptsAttemptIdRadarGetResponses];

export type ListAttemptResultsDiagnosticAdminResultsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/diagnostic/admin/results';
};

export type ListAttemptResultsDiagnosticAdminResultsGetResponses = {
    /**
     * Successful Response
     */
    200: AdminAttemptResultsResponse;
};

export type ListAttemptResultsDiagnosticAdminResultsGetResponse = ListAttemptResultsDiagnosticAdminResultsGetResponses[keyof ListAttemptResultsDiagnosticAdminResultsGetResponses];

export type GetAttemptDetailDiagnosticAdminAttemptsAttemptIdDetailGetData = {
    body?: never;
    path: {
        /**
         * Attempt Id
         */
        attempt_id: string;
    };
    query?: never;
    url: '/diagnostic/admin/attempts/{attempt_id}/detail';
};

export type GetAttemptDetailDiagnosticAdminAttemptsAttemptIdDetailGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAttemptDetailDiagnosticAdminAttemptsAttemptIdDetailGetError = GetAttemptDetailDiagnosticAdminAttemptsAttemptIdDetailGetErrors[keyof GetAttemptDetailDiagnosticAdminAttemptsAttemptIdDetailGetErrors];

export type GetAttemptDetailDiagnosticAdminAttemptsAttemptIdDetailGetResponses = {
    /**
     * Successful Response
     */
    200: AdminAttemptDetailResponse;
};

export type GetAttemptDetailDiagnosticAdminAttemptsAttemptIdDetailGetResponse = GetAttemptDetailDiagnosticAdminAttemptsAttemptIdDetailGetResponses[keyof GetAttemptDetailDiagnosticAdminAttemptsAttemptIdDetailGetResponses];

export type GetAttemptReportAdminDiagnosticAdminAttemptsAttemptIdReportGetData = {
    body?: never;
    path: {
        /**
         * Attempt Id
         */
        attempt_id: string;
    };
    query?: never;
    url: '/diagnostic/admin/attempts/{attempt_id}/report';
};

export type GetAttemptReportAdminDiagnosticAdminAttemptsAttemptIdReportGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAttemptReportAdminDiagnosticAdminAttemptsAttemptIdReportGetError = GetAttemptReportAdminDiagnosticAdminAttemptsAttemptIdReportGetErrors[keyof GetAttemptReportAdminDiagnosticAdminAttemptsAttemptIdReportGetErrors];

export type GetAttemptReportAdminDiagnosticAdminAttemptsAttemptIdReportGetResponses = {
    /**
     * Successful Response
     */
    200: DiagnosticReportResponse;
};

export type GetAttemptReportAdminDiagnosticAdminAttemptsAttemptIdReportGetResponse = GetAttemptReportAdminDiagnosticAdminAttemptsAttemptIdReportGetResponses[keyof GetAttemptReportAdminDiagnosticAdminAttemptsAttemptIdReportGetResponses];

export type BulkDeleteAttemptsDiagnosticAdminAttemptsBulkDeletePostData = {
    body: BulkDeleteAttemptsBody;
    path?: never;
    query?: never;
    url: '/diagnostic/admin/attempts/bulk-delete';
};

export type BulkDeleteAttemptsDiagnosticAdminAttemptsBulkDeletePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BulkDeleteAttemptsDiagnosticAdminAttemptsBulkDeletePostError = BulkDeleteAttemptsDiagnosticAdminAttemptsBulkDeletePostErrors[keyof BulkDeleteAttemptsDiagnosticAdminAttemptsBulkDeletePostErrors];

export type BulkDeleteAttemptsDiagnosticAdminAttemptsBulkDeletePostResponses = {
    /**
     * Successful Response
     */
    200: BulkDeleteAttemptsResponse;
};

export type BulkDeleteAttemptsDiagnosticAdminAttemptsBulkDeletePostResponse = BulkDeleteAttemptsDiagnosticAdminAttemptsBulkDeletePostResponses[keyof BulkDeleteAttemptsDiagnosticAdminAttemptsBulkDeletePostResponses];

export type ListWaitlistWaitlistGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/waitlist';
};

export type ListWaitlistWaitlistGetResponses = {
    /**
     * Response List Waitlist Waitlist Get
     * Successful Response
     */
    200: Array<WaitlistEntry>;
};

export type ListWaitlistWaitlistGetResponse = ListWaitlistWaitlistGetResponses[keyof ListWaitlistWaitlistGetResponses];

export type JoinWaitlistWaitlistPostData = {
    body: WaitlistSignupRequest;
    path?: never;
    query?: never;
    url: '/waitlist';
};

export type JoinWaitlistWaitlistPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type JoinWaitlistWaitlistPostError = JoinWaitlistWaitlistPostErrors[keyof JoinWaitlistWaitlistPostErrors];

export type JoinWaitlistWaitlistPostResponses = {
    /**
     * Successful Response
     */
    200: WaitlistSignupResponse;
};

export type JoinWaitlistWaitlistPostResponse = JoinWaitlistWaitlistPostResponses[keyof JoinWaitlistWaitlistPostResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
