// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AccountVerificationResponse
 */
export type AccountVerificationResponse = {
    /**
     * Message
     */
    message: string;
    /**
     * Redirect
     */
    redirect: boolean;
    /**
     * Token
     */
    token: string;
    user: User;
};

/**
 * BaseLevel
 */
export type BaseLevel = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
};

/**
 * BaseSubject
 */
export type BaseSubject = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Code
     */
    code: string;
    /**
     * Topics
     */
    topics: Array<BaseTopic>;
    /**
     * Papers
     */
    papers: Array<Paper>;
};

/**
 * BaseSyllabus
 */
export type BaseSyllabus = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Code
     */
    code: string;
};

/**
 * BaseTopic
 */
export type BaseTopic = {
    /**
     * Id
     */
    id: string;
    level?: BaseLevel | null;
    /**
     * Name
     */
    name: string;
    /**
     * Sortorder
     */
    sortOrder: number;
};

/**
 * Body_convert_latex_converter_post
 */
export type BodyConvertLatexConverterPost = {
    /**
     * File
     * LaTeX file to convert
     */
    file: Blob | File;
    /**
     * Title
     * Document title
     */
    title: string;
    /**
     * Difficulty
     * Document difficulty level
     */
    difficulty: string;
    /**
     * Topics
     * List of Topic Ids
     */
    topics: Array<string>;
    /**
     * Paper Instance Id
     * Paper instance ID
     */
    paper_instance_id: string;
    /**
     * Number
     * Question number within paper
     */
    number: number;
    /**
     * Marks
     * Marks allocated for this question
     */
    marks?: number | null;
    /**
     * Question Type
     * Type of question
     */
    question_type: 'default' | 'multiple_choice';
};

/**
 * ConversionResponse
 */
export type ConversionResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Documentid
     */
    documentId: string;
    /**
     * Message
     */
    message: string;
};

/**
 * CreateLevelBody
 */
export type CreateLevelBody = {
    /**
     * Name
     */
    name: string;
    /**
     * Syllabusid
     */
    syllabusId: string;
};

/**
 * CreateOptionBody
 */
export type CreateOptionBody = {
    /**
     * Value
     */
    value: string;
    /**
     * Iscorrect
     */
    isCorrect?: boolean;
    /**
     * Position
     */
    position?: number;
};

/**
 * CreatePaperBody
 */
export type CreatePaperBody = {
    /**
     * Name
     */
    name: string;
    /**
     * Subjectid
     */
    subjectId: string;
};

/**
 * CreatePaperInstanceBody
 */
export type CreatePaperInstanceBody = {
    /**
     * Paperid
     */
    paperId: string;
    /**
     * Variantid
     */
    variantId: string;
};

/**
 * CreatePaperVariantBody
 */
export type CreatePaperVariantBody = {
    /**
     * Name
     */
    name: string;
    /**
     * Year
     */
    year: number;
    /**
     * Syllabusid
     */
    syllabusId: string;
};

/**
 * CreateSubjectBody
 */
export type CreateSubjectBody = {
    /**
     * Name
     */
    name: string;
    /**
     * Code
     */
    code: string;
    /**
     * Syllabusid
     */
    syllabusId: string;
};

/**
 * CreateSyllabusBody
 */
export type CreateSyllabusBody = {
    /**
     * Name
     */
    name: string;
    /**
     * Code
     */
    code: string;
};

/**
 * CreateTopicBody
 */
export type CreateTopicBody = {
    /**
     * Name
     */
    name: string;
    /**
     * Levelid
     */
    levelId?: string | null;
    /**
     * Subjectid
     */
    subjectId: string;
    /**
     * Sortorder
     */
    sortOrder: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HintRequest
 */
export type HintRequest = {
    /**
     * Question
     */
    question: string;
    /**
     * Questionid
     */
    questionId: string;
};

/**
 * HintResponse
 */
export type HintResponse = {
    /**
     * Hint
     */
    hint: string;
    /**
     * Level
     */
    level?: number;
};

/**
 * LevelWithSyllabus
 */
export type LevelWithSyllabus = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    syllabus: BaseSyllabus;
};

/**
 * OptionResponse
 */
export type OptionResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Questionid
     */
    questionId: string;
    /**
     * Value
     */
    value: string;
    /**
     * Iscorrect
     */
    isCorrect: boolean;
    /**
     * Position
     */
    position: number;
};

/**
 * PaginatedQuestionResponse
 */
export type PaginatedQuestionResponse = {
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Size
     */
    size: number;
    /**
     * Items
     */
    items: Array<QuestionResponse>;
};

/**
 * Paper
 */
export type Paper = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
};

/**
 * PaperInstance
 */
export type PaperInstance = {
    /**
     * Id
     */
    id: string;
    paper: Paper;
    variant: PaperVariant;
};

/**
 * PaperVariant
 */
export type PaperVariant = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Year
     */
    year: number;
};

/**
 * QuestionResponse
 */
export type QuestionResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Questionurl
     */
    questionUrl: string;
    /**
     * Answerurl
     */
    answerUrl: string;
    /**
     * Difficulty
     */
    difficulty: string;
    /**
     * Createdat
     */
    createdAt: string;
    paper: Paper;
    paperVariant: PaperVariant;
    /**
     * Topics
     */
    topics: Array<BaseTopic>;
    /**
     * Number
     */
    number: number;
    /**
     * Marks
     */
    marks: number | null;
    /**
     * Status
     */
    status?: 'COMPLETED' | 'NONE' | null;
    /**
     * Type
     */
    type: 'default' | 'multiple_choice';
};

/**
 * SetCompletionResponse
 */
export type SetCompletionResponse = {
    /**
     * Issuccess
     */
    isSuccess: boolean;
    /**
     * Message
     */
    message: string;
};

/**
 * Syllabus
 */
export type Syllabus = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Code
     */
    code: string;
    /**
     * Levels
     */
    levels: Array<BaseLevel>;
    /**
     * Subjects
     */
    subjects: Array<BaseSubject>;
    /**
     * Papervariants
     */
    paperVariants: Array<PaperVariant>;
};

/**
 * UpdateOptionBody
 */
export type UpdateOptionBody = {
    /**
     * Value
     */
    value?: string | null;
    /**
     * Iscorrect
     */
    isCorrect?: boolean | null;
};

/**
 * UpdateQuestionBody
 */
export type UpdateQuestionBody = {
    /**
     * Topics
     */
    topics?: Array<string> | null;
    /**
     * Number
     */
    number?: number | null;
    /**
     * Difficulty
     */
    difficulty?: string | null;
    /**
     * Marks
     */
    marks?: number | null;
};

/**
 * UpdateTopicBody
 * Request body for updating an existing topic. All fields are optional.
 */
export type UpdateTopicBody = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Levelid
     */
    levelId?: string | null;
    /**
     * Sortorder
     */
    sortOrder?: number | null;
};

/**
 * User
 */
export type User = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Usertype
     */
    userType: 'USER' | 'ADMIN';
};

/**
 * UserLogin
 */
export type UserLogin = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserLoginResponse
 */
export type UserLoginResponse = {
    user: User;
    /**
     * Token
     */
    token: string;
    /**
     * Tokentype
     */
    tokenType?: string;
};

/**
 * UserMoreInfoForm
 */
export type UserMoreInfoForm = {
    /**
     * School
     */
    school: string;
    /**
     * State
     */
    state: 'SARAWAK' | 'SABAH' | 'TERRENGGANU' | 'KEDAH' | 'KELANTAN' | 'SELANGOR' | 'JOHOR' | 'MELAKA' | 'NEGERI SEMBILAN' | 'PENANG' | 'PERAK' | 'PAHANG' | 'PERLIS';
    /**
     * Level
     */
    level: string;
};

/**
 * UserMoreInfoResponse
 */
export type UserMoreInfoResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * UserSignup
 */
export type UserSignup = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Name
     */
    name: string;
    /**
     * Category
     */
    category: 'STUDENT' | 'PARENT' | 'TEACHER';
};

/**
 * UserSignupResponse
 */
export type UserSignupResponse = {
    /**
     * Issuccess
     */
    isSuccess: boolean;
    /**
     * Message
     */
    message: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ConvertLatexConverterPostData = {
    body: BodyConvertLatexConverterPost;
    path?: never;
    query?: never;
    url: '/converter';
};

export type ConvertLatexConverterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConvertLatexConverterPostError = ConvertLatexConverterPostErrors[keyof ConvertLatexConverterPostErrors];

export type ConvertLatexConverterPostResponses = {
    /**
     * Successful Response
     */
    200: ConversionResponse;
};

export type ConvertLatexConverterPostResponse = ConvertLatexConverterPostResponses[keyof ConvertLatexConverterPostResponses];

export type GetQuestionsByTopicQuestionsTopicsTopicIdGetData = {
    body?: never;
    path: {
        /**
         * Topic Id
         */
        topic_id: string;
    };
    query?: never;
    url: '/questions/topics/{topic_id}';
};

export type GetQuestionsByTopicQuestionsTopicsTopicIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetQuestionsByTopicQuestionsTopicsTopicIdGetError = GetQuestionsByTopicQuestionsTopicsTopicIdGetErrors[keyof GetQuestionsByTopicQuestionsTopicsTopicIdGetErrors];

export type GetQuestionsByTopicQuestionsTopicsTopicIdGetResponses = {
    /**
     * Response Get Questions By Topic Questions Topics  Topic Id  Get
     * Successful Response
     */
    200: Array<QuestionResponse>;
};

export type GetQuestionsByTopicQuestionsTopicsTopicIdGetResponse = GetQuestionsByTopicQuestionsTopicsTopicIdGetResponses[keyof GetQuestionsByTopicQuestionsTopicsTopicIdGetResponses];

export type GetQuestionsBySubjectQuestionsSubjectSubjectIdGetData = {
    body?: never;
    path: {
        /**
         * Subject Id
         */
        subject_id: string;
    };
    query?: never;
    url: '/questions/subject/{subject_id}';
};

export type GetQuestionsBySubjectQuestionsSubjectSubjectIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetQuestionsBySubjectQuestionsSubjectSubjectIdGetError = GetQuestionsBySubjectQuestionsSubjectSubjectIdGetErrors[keyof GetQuestionsBySubjectQuestionsSubjectSubjectIdGetErrors];

export type GetQuestionsBySubjectQuestionsSubjectSubjectIdGetResponses = {
    /**
     * Response Get Questions By Subject Questions Subject  Subject Id  Get
     * Successful Response
     */
    200: Array<QuestionResponse>;
};

export type GetQuestionsBySubjectQuestionsSubjectSubjectIdGetResponse = GetQuestionsBySubjectQuestionsSubjectSubjectIdGetResponses[keyof GetQuestionsBySubjectQuestionsSubjectSubjectIdGetResponses];

export type GetQuestionsBySubjectPaginatedQuestionsSubjectPaginatedSubjectIdGetData = {
    body?: never;
    path: {
        /**
         * Subject Id
         */
        subject_id: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Size
         */
        size?: number;
        /**
         * Difficulty
         * Filter by difficulty level
         */
        difficulty?: Array<string> | null;
        /**
         * Topics
         * Filter by a list of topic IDs
         */
        topics?: Array<string> | null;
        /**
         * Papers
         * Filter by a list of paper IDs. Paper 1 or Paper 2 for now.
         */
        papers?: Array<string> | null;
    };
    url: '/questions/subject/paginated/{subject_id}';
};

export type GetQuestionsBySubjectPaginatedQuestionsSubjectPaginatedSubjectIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetQuestionsBySubjectPaginatedQuestionsSubjectPaginatedSubjectIdGetError = GetQuestionsBySubjectPaginatedQuestionsSubjectPaginatedSubjectIdGetErrors[keyof GetQuestionsBySubjectPaginatedQuestionsSubjectPaginatedSubjectIdGetErrors];

export type GetQuestionsBySubjectPaginatedQuestionsSubjectPaginatedSubjectIdGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedQuestionResponse;
};

export type GetQuestionsBySubjectPaginatedQuestionsSubjectPaginatedSubjectIdGetResponse = GetQuestionsBySubjectPaginatedQuestionsSubjectPaginatedSubjectIdGetResponses[keyof GetQuestionsBySubjectPaginatedQuestionsSubjectPaginatedSubjectIdGetResponses];

export type SetQuestionStatusQuestionsSetStatusPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Question Id
         */
        question_id: string;
        /**
         * Is Completed
         */
        is_completed: boolean;
    };
    url: '/questions/set-status';
};

export type SetQuestionStatusQuestionsSetStatusPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetQuestionStatusQuestionsSetStatusPostError = SetQuestionStatusQuestionsSetStatusPostErrors[keyof SetQuestionStatusQuestionsSetStatusPostErrors];

export type SetQuestionStatusQuestionsSetStatusPostResponses = {
    /**
     * Successful Response
     */
    200: SetCompletionResponse;
};

export type SetQuestionStatusQuestionsSetStatusPostResponse = SetQuestionStatusQuestionsSetStatusPostResponses[keyof SetQuestionStatusQuestionsSetStatusPostResponses];

export type DeleteQuestionQuestionsQuestionIdDeleteData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/questions/{question_id}';
};

export type DeleteQuestionQuestionsQuestionIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteQuestionQuestionsQuestionIdDeleteError = DeleteQuestionQuestionsQuestionIdDeleteErrors[keyof DeleteQuestionQuestionsQuestionIdDeleteErrors];

export type DeleteQuestionQuestionsQuestionIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetQuestionQuestionsQuestionIdGetData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/questions/{question_id}';
};

export type GetQuestionQuestionsQuestionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetQuestionQuestionsQuestionIdGetError = GetQuestionQuestionsQuestionIdGetErrors[keyof GetQuestionQuestionsQuestionIdGetErrors];

export type GetQuestionQuestionsQuestionIdGetResponses = {
    /**
     * Successful Response
     */
    200: QuestionResponse;
};

export type GetQuestionQuestionsQuestionIdGetResponse = GetQuestionQuestionsQuestionIdGetResponses[keyof GetQuestionQuestionsQuestionIdGetResponses];

export type UpdateQuestionQuestionsQuestionIdPatchData = {
    body: UpdateQuestionBody;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/questions/{question_id}';
};

export type UpdateQuestionQuestionsQuestionIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateQuestionQuestionsQuestionIdPatchError = UpdateQuestionQuestionsQuestionIdPatchErrors[keyof UpdateQuestionQuestionsQuestionIdPatchErrors];

export type UpdateQuestionQuestionsQuestionIdPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetQuestionsByPaperInstanceQuestionsPaperInstancePaperInstanceIdGetData = {
    body?: never;
    path: {
        /**
         * Paper Instance Id
         */
        paper_instance_id: string;
    };
    query?: never;
    url: '/questions/paper_instance/{paper_instance_id}';
};

export type GetQuestionsByPaperInstanceQuestionsPaperInstancePaperInstanceIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetQuestionsByPaperInstanceQuestionsPaperInstancePaperInstanceIdGetError = GetQuestionsByPaperInstanceQuestionsPaperInstancePaperInstanceIdGetErrors[keyof GetQuestionsByPaperInstanceQuestionsPaperInstancePaperInstanceIdGetErrors];

export type GetQuestionsByPaperInstanceQuestionsPaperInstancePaperInstanceIdGetResponses = {
    /**
     * Response Get Questions By Paper Instance Questions Paper Instance  Paper Instance Id  Get
     * Successful Response
     */
    200: Array<QuestionResponse>;
};

export type GetQuestionsByPaperInstanceQuestionsPaperInstancePaperInstanceIdGetResponse = GetQuestionsByPaperInstanceQuestionsPaperInstancePaperInstanceIdGetResponses[keyof GetQuestionsByPaperInstanceQuestionsPaperInstancePaperInstanceIdGetResponses];

export type GetQuestionOptionsQuestionsQuestionIdOptionsGetData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/questions/{question_id}/options';
};

export type GetQuestionOptionsQuestionsQuestionIdOptionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetQuestionOptionsQuestionsQuestionIdOptionsGetError = GetQuestionOptionsQuestionsQuestionIdOptionsGetErrors[keyof GetQuestionOptionsQuestionsQuestionIdOptionsGetErrors];

export type GetQuestionOptionsQuestionsQuestionIdOptionsGetResponses = {
    /**
     * Response Get Question Options Questions  Question Id  Options Get
     * Successful Response
     */
    200: Array<OptionResponse>;
};

export type GetQuestionOptionsQuestionsQuestionIdOptionsGetResponse = GetQuestionOptionsQuestionsQuestionIdOptionsGetResponses[keyof GetQuestionOptionsQuestionsQuestionIdOptionsGetResponses];

export type CreateOptionQuestionsQuestionIdOptionPostData = {
    body: CreateOptionBody;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/questions/{question_id}/option';
};

export type CreateOptionQuestionsQuestionIdOptionPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateOptionQuestionsQuestionIdOptionPostError = CreateOptionQuestionsQuestionIdOptionPostErrors[keyof CreateOptionQuestionsQuestionIdOptionPostErrors];

export type CreateOptionQuestionsQuestionIdOptionPostResponses = {
    /**
     * Successful Response
     */
    200: OptionResponse;
};

export type CreateOptionQuestionsQuestionIdOptionPostResponse = CreateOptionQuestionsQuestionIdOptionPostResponses[keyof CreateOptionQuestionsQuestionIdOptionPostResponses];

export type DeleteOptionQuestionsQuestionIdOptionOptionIdDeleteData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: string;
        /**
         * Option Id
         */
        option_id: string;
    };
    query?: never;
    url: '/questions/{question_id}/option/{option_id}';
};

export type DeleteOptionQuestionsQuestionIdOptionOptionIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteOptionQuestionsQuestionIdOptionOptionIdDeleteError = DeleteOptionQuestionsQuestionIdOptionOptionIdDeleteErrors[keyof DeleteOptionQuestionsQuestionIdOptionOptionIdDeleteErrors];

export type DeleteOptionQuestionsQuestionIdOptionOptionIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: OptionResponse;
};

export type DeleteOptionQuestionsQuestionIdOptionOptionIdDeleteResponse = DeleteOptionQuestionsQuestionIdOptionOptionIdDeleteResponses[keyof DeleteOptionQuestionsQuestionIdOptionOptionIdDeleteResponses];

export type UpdateOptionQuestionsQuestionIdOptionOptionIdPatchData = {
    body: UpdateOptionBody;
    path: {
        /**
         * Question Id
         */
        question_id: string;
        /**
         * Option Id
         */
        option_id: string;
    };
    query?: never;
    url: '/questions/{question_id}/option/{option_id}';
};

export type UpdateOptionQuestionsQuestionIdOptionOptionIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateOptionQuestionsQuestionIdOptionOptionIdPatchError = UpdateOptionQuestionsQuestionIdOptionOptionIdPatchErrors[keyof UpdateOptionQuestionsQuestionIdOptionOptionIdPatchErrors];

export type UpdateOptionQuestionsQuestionIdOptionOptionIdPatchResponses = {
    /**
     * Successful Response
     */
    200: OptionResponse;
};

export type UpdateOptionQuestionsQuestionIdOptionOptionIdPatchResponse = UpdateOptionQuestionsQuestionIdOptionOptionIdPatchResponses[keyof UpdateOptionQuestionsQuestionIdOptionOptionIdPatchResponses];

export type GetAllSyllabusSyllabusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/syllabus';
};

export type GetAllSyllabusSyllabusGetResponses = {
    /**
     * Response Get All Syllabus Syllabus Get
     * Successful Response
     */
    200: Array<Syllabus>;
};

export type GetAllSyllabusSyllabusGetResponse = GetAllSyllabusSyllabusGetResponses[keyof GetAllSyllabusSyllabusGetResponses];

export type CreateSyllabusSyllabusPostData = {
    body: CreateSyllabusBody;
    path?: never;
    query?: never;
    url: '/syllabus';
};

export type CreateSyllabusSyllabusPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSyllabusSyllabusPostError = CreateSyllabusSyllabusPostErrors[keyof CreateSyllabusSyllabusPostErrors];

export type CreateSyllabusSyllabusPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSyllabusSyllabusSyllabusIdGetData = {
    body?: never;
    path: {
        /**
         * Syllabus Id
         */
        syllabus_id: string;
    };
    query?: never;
    url: '/syllabus/{syllabus_id}';
};

export type GetSyllabusSyllabusSyllabusIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSyllabusSyllabusSyllabusIdGetError = GetSyllabusSyllabusSyllabusIdGetErrors[keyof GetSyllabusSyllabusSyllabusIdGetErrors];

export type GetSyllabusSyllabusSyllabusIdGetResponses = {
    /**
     * Successful Response
     */
    200: Syllabus;
};

export type GetSyllabusSyllabusSyllabusIdGetResponse = GetSyllabusSyllabusSyllabusIdGetResponses[keyof GetSyllabusSyllabusSyllabusIdGetResponses];

export type GetSubjectSubjectsSubjectIdGetData = {
    body?: never;
    path: {
        /**
         * Subject Id
         */
        subject_id: string;
    };
    query?: never;
    url: '/subjects/{subject_id}';
};

export type GetSubjectSubjectsSubjectIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSubjectSubjectsSubjectIdGetError = GetSubjectSubjectsSubjectIdGetErrors[keyof GetSubjectSubjectsSubjectIdGetErrors];

export type GetSubjectSubjectsSubjectIdGetResponses = {
    /**
     * Successful Response
     */
    200: BaseSubject;
};

export type GetSubjectSubjectsSubjectIdGetResponse = GetSubjectSubjectsSubjectIdGetResponses[keyof GetSubjectSubjectsSubjectIdGetResponses];

export type CreateSubjectSubjectsPostData = {
    body: CreateSubjectBody;
    path?: never;
    query?: never;
    url: '/subjects';
};

export type CreateSubjectSubjectsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSubjectSubjectsPostError = CreateSubjectSubjectsPostErrors[keyof CreateSubjectSubjectsPostErrors];

export type CreateSubjectSubjectsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetAllLevelsLevelsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/levels';
};

export type GetAllLevelsLevelsGetResponses = {
    /**
     * Response Get All Levels Levels Get
     * Successful Response
     */
    200: Array<LevelWithSyllabus>;
};

export type GetAllLevelsLevelsGetResponse = GetAllLevelsLevelsGetResponses[keyof GetAllLevelsLevelsGetResponses];

export type CreateLevelLevelsPostData = {
    body: CreateLevelBody;
    path?: never;
    query?: never;
    url: '/levels';
};

export type CreateLevelLevelsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateLevelLevelsPostError = CreateLevelLevelsPostErrors[keyof CreateLevelLevelsPostErrors];

export type CreateLevelLevelsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteLevelLevelsLevelIdDeleteData = {
    body?: never;
    path: {
        /**
         * Level Id
         */
        level_id: string;
    };
    query?: never;
    url: '/levels/{level_id}';
};

export type DeleteLevelLevelsLevelIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteLevelLevelsLevelIdDeleteError = DeleteLevelLevelsLevelIdDeleteErrors[keyof DeleteLevelLevelsLevelIdDeleteErrors];

export type DeleteLevelLevelsLevelIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetTopicsBySubjectTopicsSubjectIdGetData = {
    body?: never;
    path: {
        /**
         * Subject Id
         */
        subject_id: string;
    };
    query?: never;
    url: '/topics/{subject_id}';
};

export type GetTopicsBySubjectTopicsSubjectIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTopicsBySubjectTopicsSubjectIdGetError = GetTopicsBySubjectTopicsSubjectIdGetErrors[keyof GetTopicsBySubjectTopicsSubjectIdGetErrors];

export type GetTopicsBySubjectTopicsSubjectIdGetResponses = {
    /**
     * Response Get Topics By Subject Topics  Subject Id  Get
     * Successful Response
     */
    200: Array<BaseTopic>;
};

export type GetTopicsBySubjectTopicsSubjectIdGetResponse = GetTopicsBySubjectTopicsSubjectIdGetResponses[keyof GetTopicsBySubjectTopicsSubjectIdGetResponses];

export type CreateTopicTopicsPostData = {
    body: CreateTopicBody;
    path?: never;
    query?: never;
    url: '/topics';
};

export type CreateTopicTopicsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTopicTopicsPostError = CreateTopicTopicsPostErrors[keyof CreateTopicTopicsPostErrors];

export type CreateTopicTopicsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteTopicTopicsTopicIdDeleteData = {
    body?: never;
    path: {
        /**
         * Topic Id
         */
        topic_id: string;
    };
    query?: never;
    url: '/topics/{topic_id}';
};

export type DeleteTopicTopicsTopicIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTopicTopicsTopicIdDeleteError = DeleteTopicTopicsTopicIdDeleteErrors[keyof DeleteTopicTopicsTopicIdDeleteErrors];

export type DeleteTopicTopicsTopicIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateTopicTopicsTopicIdPatchData = {
    body: UpdateTopicBody;
    path: {
        /**
         * Topic Id
         */
        topic_id: string;
    };
    query?: never;
    url: '/topics/{topic_id}';
};

export type UpdateTopicTopicsTopicIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTopicTopicsTopicIdPatchError = UpdateTopicTopicsTopicIdPatchErrors[keyof UpdateTopicTopicsTopicIdPatchErrors];

export type UpdateTopicTopicsTopicIdPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreatePaperPapersPostData = {
    body: CreatePaperBody;
    path?: never;
    query?: never;
    url: '/papers';
};

export type CreatePaperPapersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePaperPapersPostError = CreatePaperPapersPostErrors[keyof CreatePaperPapersPostErrors];

export type CreatePaperPapersPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeletePaperPapersPaperIdDeleteData = {
    body?: never;
    path: {
        /**
         * Paper Id
         */
        paper_id: string;
    };
    query?: never;
    url: '/papers/{paper_id}';
};

export type DeletePaperPapersPaperIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePaperPapersPaperIdDeleteError = DeletePaperPapersPaperIdDeleteErrors[keyof DeletePaperPapersPaperIdDeleteErrors];

export type DeletePaperPapersPaperIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeletePaperPapersInstanceInstanceIdDeleteData = {
    body?: never;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
    };
    query?: never;
    url: '/papers/instance/{instance_id}';
};

export type DeletePaperPapersInstanceInstanceIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePaperPapersInstanceInstanceIdDeleteError = DeletePaperPapersInstanceInstanceIdDeleteErrors[keyof DeletePaperPapersInstanceInstanceIdDeleteErrors];

export type DeletePaperPapersInstanceInstanceIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPaperInstancePapersInstanceInstanceIdGetData = {
    body?: never;
    path: {
        /**
         * Instance Id
         */
        instance_id: string;
    };
    query?: never;
    url: '/papers/instance/{instance_id}';
};

export type GetPaperInstancePapersInstanceInstanceIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPaperInstancePapersInstanceInstanceIdGetError = GetPaperInstancePapersInstanceInstanceIdGetErrors[keyof GetPaperInstancePapersInstanceInstanceIdGetErrors];

export type GetPaperInstancePapersInstanceInstanceIdGetResponses = {
    /**
     * Successful Response
     */
    200: PaperInstance;
};

export type GetPaperInstancePapersInstanceInstanceIdGetResponse = GetPaperInstancePapersInstanceInstanceIdGetResponses[keyof GetPaperInstancePapersInstanceInstanceIdGetResponses];

export type GetPaperInstancesBySubjectIdPapersInstanceSubjectSubjectIdGetData = {
    body?: never;
    path: {
        /**
         * Subject Id
         */
        subject_id: string;
    };
    query?: never;
    url: '/papers/instance/subject/{subject_id}';
};

export type GetPaperInstancesBySubjectIdPapersInstanceSubjectSubjectIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPaperInstancesBySubjectIdPapersInstanceSubjectSubjectIdGetError = GetPaperInstancesBySubjectIdPapersInstanceSubjectSubjectIdGetErrors[keyof GetPaperInstancesBySubjectIdPapersInstanceSubjectSubjectIdGetErrors];

export type GetPaperInstancesBySubjectIdPapersInstanceSubjectSubjectIdGetResponses = {
    /**
     * Response Get Paper Instances By Subject Id Papers Instance Subject  Subject Id  Get
     * Successful Response
     */
    200: Array<PaperInstance>;
};

export type GetPaperInstancesBySubjectIdPapersInstanceSubjectSubjectIdGetResponse = GetPaperInstancesBySubjectIdPapersInstanceSubjectSubjectIdGetResponses[keyof GetPaperInstancesBySubjectIdPapersInstanceSubjectSubjectIdGetResponses];

export type CreatePaperInstancePapersInstancePostData = {
    body: CreatePaperInstanceBody;
    path?: never;
    query?: never;
    url: '/papers/instance';
};

export type CreatePaperInstancePapersInstancePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePaperInstancePapersInstancePostError = CreatePaperInstancePapersInstancePostErrors[keyof CreatePaperInstancePapersInstancePostErrors];

export type CreatePaperInstancePapersInstancePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreatePaperVariantPapersVariantPostData = {
    body: CreatePaperVariantBody;
    path?: never;
    query?: never;
    url: '/papers/variant';
};

export type CreatePaperVariantPapersVariantPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePaperVariantPapersVariantPostError = CreatePaperVariantPapersVariantPostErrors[keyof CreatePaperVariantPapersVariantPostErrors];

export type CreatePaperVariantPapersVariantPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteVariantPapersVariantVariantIdDeleteData = {
    body?: never;
    path: {
        /**
         * Variant Id
         */
        variant_id: string;
    };
    query?: never;
    url: '/papers/variant/{variant_id}';
};

export type DeleteVariantPapersVariantVariantIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteVariantPapersVariantVariantIdDeleteError = DeleteVariantPapersVariantVariantIdDeleteErrors[keyof DeleteVariantPapersVariantVariantIdDeleteErrors];

export type DeleteVariantPapersVariantVariantIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SignupUsersPostData = {
    body: UserSignup;
    path?: never;
    query?: never;
    url: '/users';
};

export type SignupUsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SignupUsersPostError = SignupUsersPostErrors[keyof SignupUsersPostErrors];

export type SignupUsersPostResponses = {
    /**
     * Successful Response
     */
    200: UserSignupResponse;
};

export type SignupUsersPostResponse = SignupUsersPostResponses[keyof SignupUsersPostResponses];

export type LoginUsersLoginPostData = {
    body: UserLogin;
    path?: never;
    query?: never;
    url: '/users/login';
};

export type LoginUsersLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginUsersLoginPostError = LoginUsersLoginPostErrors[keyof LoginUsersLoginPostErrors];

export type LoginUsersLoginPostResponses = {
    /**
     * Successful Response
     */
    200: UserLoginResponse;
};

export type LoginUsersLoginPostResponse = LoginUsersLoginPostResponses[keyof LoginUsersLoginPostResponses];

export type VerifyEmailUsersVerifyPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Token
         */
        token: string;
    };
    url: '/users/verify';
};

export type VerifyEmailUsersVerifyPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerifyEmailUsersVerifyPostError = VerifyEmailUsersVerifyPostErrors[keyof VerifyEmailUsersVerifyPostErrors];

export type VerifyEmailUsersVerifyPostResponses = {
    /**
     * Successful Response
     */
    200: AccountVerificationResponse;
};

export type VerifyEmailUsersVerifyPostResponse = VerifyEmailUsersVerifyPostResponses[keyof VerifyEmailUsersVerifyPostResponses];

export type ResendVerificationUsersResendVerificationPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email
         */
        email: string;
    };
    url: '/users/resend-verification';
};

export type ResendVerificationUsersResendVerificationPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResendVerificationUsersResendVerificationPostError = ResendVerificationUsersResendVerificationPostErrors[keyof ResendVerificationUsersResendVerificationPostErrors];

export type ResendVerificationUsersResendVerificationPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type MoreInfoUsersMoreInfoPostData = {
    body: UserMoreInfoForm;
    path?: never;
    query?: never;
    url: '/users/more-info';
};

export type MoreInfoUsersMoreInfoPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MoreInfoUsersMoreInfoPostError = MoreInfoUsersMoreInfoPostErrors[keyof MoreInfoUsersMoreInfoPostErrors];

export type MoreInfoUsersMoreInfoPostResponses = {
    /**
     * Successful Response
     */
    200: UserMoreInfoResponse;
};

export type MoreInfoUsersMoreInfoPostResponse = MoreInfoUsersMoreInfoPostResponses[keyof MoreInfoUsersMoreInfoPostResponses];

export type GetCurrentUserUsersCurrentGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/current';
};

export type GetCurrentUserUsersCurrentGetResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type GetCurrentUserUsersCurrentGetResponse = GetCurrentUserUsersCurrentGetResponses[keyof GetCurrentUserUsersCurrentGetResponses];

export type GetHintChatHintPostData = {
    body: HintRequest;
    path?: never;
    query?: never;
    url: '/chat/hint';
};

export type GetHintChatHintPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetHintChatHintPostError = GetHintChatHintPostErrors[keyof GetHintChatHintPostErrors];

export type GetHintChatHintPostResponses = {
    /**
     * Successful Response
     */
    200: HintResponse;
};

export type GetHintChatHintPostResponse = GetHintChatHintPostResponses[keyof GetHintChatHintPostResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
